### PR TITLE
Add webflux

### PR DESCRIPTION
**Pull request by Bolo89**
- https://github.com/jhipster/jhipster-lite/issues/1223 (part 1/3)

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Missing key/value in application.properties, like server.port

**Review by fdelbrayelle — APPROVED** [review]
Nice work!

**Review by pascalgrimaud — APPROVED** [review]

**Comment by Bolo89** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/73745

**Comment by pascalgrimaud** [comment]
@Bolo89 : approved

**Pull request merged**
