### PR TITLE
Add radius to connectors in landscape

### LINKED ISSUE #3967: Add radius to landscape connectors
Update landscape connectors to have small radius (it should be better looking). Need to use SVG path for that

### PR DESCRIPTION
**Pull request by swarajsaaj**
Add radius using <path> instead of <polyline> in SVG connectors.

Fix #3967

### CODE REVIEW

**Comment by DamnClin** [comment]
Wow, amazing! Can you send a screenshot of the new version?

**Review by DamnClin — APPROVED** [review]

**Comment by swarajsaaj** [comment]
Hi,
It looks like this now:-
Compact:-
image

Extended:-
image

**Comment by DamnClin** [comment]
Ok for me, don't forget to claim your $100 bounty :)

**Comment by swarajsaaj** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/105817

**Comment by pascalgrimaud** [comment]
@swarajsaaj : approved

**Pull request merged**
