### PR TITLE
Commit module application

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2733

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Following this, the SonarCloud analysis failed:
Screenshot_20220728-062811

It wasn't detect in the CI because we still use Sonar 9.4 and Sonarcloud uses probably 9.5

Can you have a look plz @DamnClin ?
Otherwise, I should find time at the end of this morning

**Comment by DamnClin** [comment]
I can check but knowing the issues would help

**Comment by pascalgrimaud** [comment]
Yes, the analysis is public: https://sonarcloud.io/project/overview?id=jhipster_jhipster-lite

**Comment by DamnClin** [comment]
I think I don't know how to read the report because for me this was not caused by this PR and this code was there for a very long time

**Comment by pascalgrimaud** [comment]
No worry and you're right, maybe it was not because of this PR as Sonarcloud can upgrade and change some rules, so it can happen :-D

**Comment by DamnClin** [comment]
The rule is basivcally saying we can't write to user manage path. So I'll just disable it since it is JHlite job do to that

**Pull request merged**
