### PR TITLE
fix(ci): prevent code injection by using the commit message or the pu…

### PR DESCRIPTION
**Pull request by renanfranca**
…ll request.

Here are some tests proving it is working:
- [Pull request title: a"; ls $GITHUB_WORKSPACE](https://github.com/renanfranca/jhipster-lite/actions/runs/9467972788/job/26083305738?pr=20)
-  [Pull request title: 'echo test'](https://github.com/renanfranca/jhipster-lite/actions/runs/9468020756/job/26083453422?pr=20)
-  [Pull request title: test to [ignore ci]](https://github.com/renanfranca/jhipster-lite/actions/runs/9468073004/job/26083621521?pr=20)

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Adding a bounty for this important fix

**Comment by renanfranca** [comment]
> Adding a bounty for this important fix

Thank you very much @pascalgrimaud ! 😃👍

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/209366. Thanks 😃🖖

**Comment by pascalgrimaud** [comment]
@renanfranca : approved

**Pull request merged**
