### PR TITLE
Handle temporary directory ending with slash

### PR DESCRIPTION
**Pull request by DanielFran**
@pascalgrimaud Can you check if it is OK for you?

Before:
````
 .../Temp//jhlite-test/...
````
image

After:
````
 .../Temp/jhlite-test/...
````
image

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
yes looks fine !

**Comment by pascalgrimaud** [comment]
Anyway, I predict you won't pass the CI. We'll see it, in few minutes ;)

**Comment by DanielFran** [comment]
Probably because I do not have tests for it ;)

**Comment by DanielFran** [comment]
@pascalgrimaud This is now ready :)

**Pull request merged**
