### PR TITLE
Migrate mssql domain service to new module system

### PR DESCRIPTION
**Pull request by DanielFran**
Fix https://github.com/jhipster/jhipster-lite/issues/2119

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@DanielFran : can you fix the CI plz?

**Comment by DamnClin** [comment]
/!\ breaking change incomming. In https://github.com/jhipster/jhipster-lite/pull/2500 the dependency method become addDependency. I can add some method for migration phase if you want

**Comment by pascalgrimaud** [comment]
bad "rebase" or "merge remote" :-(

image

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/jhipster-lite/pull/2547

**Pull request closed without merging**
