### PR TITLE
Angular 16.2.4

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #7406 #7407 

@murdos you can close this PR if you need to test #7397

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Oh sorry I merged the other PR before
What can I do now?

**Comment by qmonmert** [comment]
@pascalgrimaud maybe not merging this PR and wait tomorrow to see if the PR of @murdos works 🙂

**Comment by pascalgrimaud** [comment]
nice, let's wait tomorrow :)

**Comment by pascalgrimaud** [comment]
looks fine I think, so let's close this

**Pull request closed without merging**
