### PR TITLE
bump jsdom from 21.0.0 to 21.1.0

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #5111

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud can you test this PR, because I don't understand if I broke something on the interface 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : I'll have a look this morning

**Comment by pascalgrimaud** [comment]
seems good

**Comment by qmonmert** [comment]
@pascalgrimaud ok thanks

**Pull request merged**
