### PR TITLE
Add documentation link

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2833

### CODE REVIEW

**Comment by DamnClin** [comment]
cc @jdubois with this you have an updated usage guide and link to it in the app (if you want to deploy). Far from being perfect but we still have a long way to go to the modules hierarchy :) (see https://github.com/jhipster/jhipster-lite/discussions/2671).

BTW is there an easy way to have CD for this app?

**Comment by jdubois** [comment]
@DamnClin I'm not sure what is the best option, as I do this on my fork with my own Azure account -> how about having a GitHub Action that syncs this daily?

**Comment by DamnClin** [comment]
Can do if it's easier to build that a github action here deploying after main build (which would be the first option for me).

**Comment by jdubois** [comment]
My issue is that I can't share my secret token on an OSS repo (not that I don't trust you, but it's for security compliance)

**Comment by DamnClin** [comment]
Totally understandable! We can start like that and change the trigger later on to a trigger at the end of main build here

**Pull request merged**
