### PR TITLE
Spring-boot 3.1.0

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #6317

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Adding a bounty, as we need this for a new release

**Comment by pascalgrimaud** [comment]
@qmonmert : just fix mongodb directly in your branch. Hope the CI will pass

**Comment by qmonmert** [comment]
@pascalgrimaud thanks, I tried to fix this morning but I did not find

**Comment by qmonmert** [comment]
https://opencollective.com/generator-jhipster/expenses/140021 @pascalgrimaud 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Pull request merged**
