### PR TITLE
Spring-boot: use get version, managed by dependabot

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
Stuck with current approach for the tests as buildTool is empty.

image

@pascalgrimaud using project created from a pom.xml should define buildTool as maven service?

**Comment by pascalgrimaud** [comment]
All these fields are currently not used, it's planned but not done yet today.
It will be needed once we want to orchestrate all different calls to generate the project in one single shot

**Comment by pascalgrimaud** [comment]
If you need, I can have a look at your branch and take care of failed tests.
just tell me :)

**Comment by DanielFran** [comment]
Feel free to add changes, it will speed up since I have few time...

**Pull request merged**
