### PR TITLE
fix native hints for jgit integration

### PR DESCRIPTION
**Pull request by atomfrede**
Correct the resourcebundle hint for jgit and add another class which is needs reflection config from jgit 6.5 and up.

relates to #6102

### CODE REVIEW

**Review by DamnClin — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Thanks @atomfrede 
I added a bounty, as I know we can spend time to analyse the behavior with GraalVM. Don't hesitate to ping me if you think it's not enough

**Comment by atomfrede** [comment]
Thanks @pascalgrimaud!

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/136905

**Comment by pascalgrimaud** [comment]
@atomfrede : approved

**Pull request merged**
