### PR TITLE
chore(deps): update generated apps to spring-boot 3.4.0

### PR DESCRIPTION
**Pull request by murdos**
Closes #11424

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@murdos : can you rebase plz?

**Comment by murdos** [comment]
@pascalgrimaud : done :)

**Comment by pascalgrimaud** [comment]
Related to https://github.com/jhipster/jhipster-lite/issues/11403

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
