### PR TITLE
Pulsar: use spring-boot-starter-pulsar

### PR DESCRIPTION
**Pull request by qmonmert**
Related to my discussion on this ticket https://github.com/apache/pulsar/issues/23509

Related to #11184

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
if it works, look good to me, to apply this change.
I don't remember the initial author of pulsar module?

**Comment by qmonmert** [comment]
> if it works, look good to me, to apply this change. I don't remember the initial author of pulsar module?

👍
I don't remember either

**Comment by pascalgrimaud** [comment]
Found this initial PR: https://github.com/jhipster/jhipster-lite/pull/1745

Cc @cbornet : does it look good for you, to migrate from native pulsar lib to spring boot starter ?

**Review by murdos — APPROVED** [review]

**Comment by qmonmert** [comment]
@cbornet can you review this PR? 🙂

**Pull request merged**
