### PR TITLE
Angular 16.1.5

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #6876

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
adding a bounty for all your recent work in JHipster Lite project

**Comment by pascalgrimaud** [comment]
some trouble with codecov today, I'm restarting it, until it passes

**Comment by qmonmert** [comment]
after merge https://opencollective.com/generator-jhipster/expenses/149883 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved, thanks for all your work

**Pull request merged**
