### PR TITLE
Property has been removed

### PR DESCRIPTION
**Pull request by Saravana-PS**
@pascalgrimaud As per our discussion, I have removed the property `spring.security.oauth2.client.registration.oidc.scope` from the Actuator module (#6942).

### CODE REVIEW

**Comment by Saravana-PS** [comment]
Hi @pascalgrimaud, Kindly advise me on why some checks were not successful.

**Comment by pascalgrimaud** [comment]
@Saravana-PS : have a look at the test `SpringBootActuatorModuleFactoryTest`, as you need to update it too

**Comment by Saravana-PS** [comment]
> 

@pascalgrimaud  Oh got it. I will update it.

**Comment by pascalgrimaud** [comment]
Still this file to update: src/test/features/springboot-actuator.feature

Just run locally `./mvnw clean verify` so you'll check locally what's wrong :)

**Comment by pascalgrimaud** [comment]
Thanks for your contribution :-)

**Pull request merged**
