### PR TITLE
Improve ci to not launch same tests

### LINKED ISSUE #6651: Improve CI to not launch same tests
For each builds, we should compare:
- the hash of the generated project from main branch
- the hash of the generated project from pull request
- if it's different, launch the build
- otherwise, it should be success

With this change, we won't launch same builds for each pull requests

### PR DESCRIPTION
**Pull request by renanfranca**
Fix #6651

### CODE REVIEW

**Comment by renanfranca** [comment]
@pascalgrimaud : The tests from the generated app will run if the generated app from the main branch is different from the pull request branch.

Only three apps generated from the CI process - consulapp, eurekaapp, and gatewayapp - will always run the tests.

consulapp always generate a new base64-secret:
`diff -r --exclude='.git' --exclude='.github' --exclude='.jhipster' --exclude='node_modules' --exclude='target' --exclude='build' /tmp/cicd/main/consulapp /tmp/cicd/pullrequest/consulapp`

```bash
/tmp/cicd/main/consulapp/src/main/docker/central-server-config/application.yml /tmp/cicd/pullrequest/consulapp/src/main/docker/central-server-config/application.yml
13c13
< #         base64-secret: ZDM5MWU4NThiY2MyYWQ4N2QzNjE5ZWVmZGE2ZmY3YTk2ZDI0MTVmOTNhMTdmZjdlMTY2ZTIyNzFiMzBjNWVkNw==
---
> #         base64-secret: ZmYxOTBlMzc4ODg2YTcwYTYyZWMzNjBiZGE0ZWVmZTM4MzljMzYwZDk4NzhmZDhlNmQ0MGIwNGY2NjkzNWE3Yg==
```

eurekaapp always generate a new jhipster.security.authentication.jwt:
`diff -r --exclude='.git' --exclude='.github' --exclude='.jhipster' --exclude='node_modules' --exclude='target' --exclude='build' /tmp/cicd/main/eurekaapp /tmp/cicd/pullrequest/eurekaapp`

```bash
/tmp/cicd/main/eurekaapp/src/main/docker/central-server-config/localhost-config/application.properties /tmp/cicd/pullrequest/eurekaapp/src/main/docker/central-server-config/localhost-config/application.properties
5c5
< jhipster.security.authentication.jwt.base64-secret=MTY2MjVmN2Q0NmQwNTJkYWM3ZmU3MjEwZWY2NzdmOGYzYjM5Y2I1ZjA3NjllZWJiNGRkNDNjNjE4Mjc4ZTkyYQ==
---
> jhipster.security.authentication.jwt.base64-secret=OGY4YzA5OTI1OTI0ZmU5MDExYjQ3OTE0YTAyYWU2NzU4ODJlNzM3MDg0NzRkMzY3YzQ0NDAwZmIyODgxN2JiNQ==
```

gatewayapp always generate a new jhipster.security.authentication.jwt:
`diff -r --exclude='.git' --exclude='.github' --exclude='.jhipster' --exclude='node_modules' --exclude='target' --exclude='build' /tmp/cicd/main/gatewayapp /tmp/cicd/pullrequest/gatewayapp`

```bash
/tmp/cicd/main/gatewayapp/src/main/docker/central-server-config/localhost-config/application.properties /tmp/cicd/pullrequest/gatewayapp/src/main/docker/central-server-config/localhost-config/application.properties
5c5
< jhipster.security.authentication.jwt.base64-secret=MTFjNmZjZjU2YzgzZmFlMzVhOGE5ZmJiODIyZmUyZWEyZGY4NjNlMGFhMjY3ZTNjZDY5NWM2ZTdhNTU4ZmQyMQ==
---
> jhipster.security.authentication.jwt.base64-secret=ZDdlOWUwZWU0OTVkYzFlYWVlYTYyZDY3ODJkOTA0MTdjZTYxYmQ0NzljNmVmYTJhZWZlMTQ1NTI0MGY2YzA0NA==
```

**Comment by murdos** [comment]
Awesome improvement @renanfranca ! 
IMO the 3 generated apps that still change on each generation could be fixed later, in a separate PR, this would already reduce CI load.

**Comment by renanfranca** [comment]
> Awesome improvement @renanfranca ! 
> IMO the 3 generated apps that still change on each generation could be fixed later, in a separate PR, this would already reduce CI load.

@murdos : Thank you very much! This issue was a big challenge for me, but solving it has really motivated me!According to my tests, it saved 4 minutes in the pipeline, but it will be interesting to follow the next pull requests that will run with these new changes.

We should discuss later how to deal with these 3 apps, I don't have a clear approach for it right now.

**Comment by pascalgrimaud** [comment]
About the 3 apps, it's my fault, I already did the work but didn't report it to these 3 modules.
You can have a look at:
- https://github.com/jhipster/jhipster-lite/issues/6899
- https://github.com/jhipster/jhipster-lite/pull/6931

image


You can add a fixed configuration (secret, or date) in JSON config:
- https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/modulePayload.json#L8-L9

These modules should use this configuration when it exists. If not, it will generate these values

These improvement can be done in another PR, not this one plz :)

**Comment by renanfranca** [comment]
> About the 3 apps, it's my fault, I already did the work but didn't report it to these 3 modules.
> You can have a look at:
> - https://github.com/jhipster/jhipster-lite/issues/6899
> - https://github.com/jhipster/jhipster-lite/pull/6931
> 
> image
> 
> 
> You can add a fixed configuration (secret, or date) in JSON config:
> - https://github.com/jhipster/jhipster-lite/blob/main/tests-ci/modulePayload.json#L8-L9
> 
> These modules should use this configuration when it exists. If not, it will generate these values
> 
> These improvement can be done in another PR, not this one plz :)

@pascalgrimaud : Nice! I will do it in another PR! 😄

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/183746 . Thanks 😄 ✌️

**Comment by pascalgrimaud** [comment]
@renanfranca : approved

**Pull request merged**
