### PR TITLE
Add upgrade feature

### PR DESCRIPTION
**Pull request by DamnClin**
Related to https://github.com/jhipster/jhipster-lite/issues/5606

First step for upgrade feature, added the domain part (still need WebServices, cli, screens, integration on modules, etc)

### CODE REVIEW

**Comment by DamnClin** [comment]
Coverage drop due to maven dependencies management refactoring. I'll have a look at it but not soon...

**Comment by pascalgrimaud** [comment]
Thanks for the work @DamnClin 
I'll try to have a look soon, but if you need it, don't hesitate to go ahead and merge it

**Comment by DamnClin** [comment]
> Thanks for the work @DamnClin I'll try to have a look soon, but if you need it, don't hesitate to go ahead and merge it

Really busy on other subjects for the upcoming weeks, no rush

**Comment by renanfranca** [comment]
Sorry for taking too long to review this pull request. I think it is ready to merge, I have no suggestions to improve the code 😃 👍 

Thank you for keeping bring new features to the project 👏

**Comment by pascalgrimaud** [comment]
The last comments can be done in another PR I think
Let's merge this

**Pull request merged**
