### PR TITLE
add initial playwright configuration

### LINKED ISSUE #1296: Add playwright as additional e2e framework
I love playwright and I think it would be nice to have it here. There will be a blueprint for the jhipster "large" generator, but it takes more time to rewrite the tests. WDYT?

### PR DESCRIPTION
**Pull request by atomfrede**
Initial playwright configuration with one spec and page object model.

closes #1296

### CODE REVIEW

**Comment by atomfrede** [comment]
Will check the code smells tomorrow. And of course, as we talked about it this morning, sonar images are not available as arm64. So much for no problems with M1 macs and docker :)

**Comment by pascalgrimaud** [comment]
Impressive work @atomfrede !
You're so fast lol 

I'll review it soon :)

**Comment by pascalgrimaud** [comment]
I think the front is stable now, so in another PRs, we can add this to the front part:
- front: secondary with api
- front: primary + the button in Vue page

**Review by pascalgrimaud — APPROVED** [review]

**Comment by atomfrede** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/73021

**Comment by pascalgrimaud** [comment]
@atomfrede : approved

**Pull request merged**
