### PR TITLE
Automatic module URLs

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2003
Close https://github.com/jhipster/jhipster-lite/issues/2038
Related to https://github.com/jhipster/jhipster-lite/issues/1565

### CODE REVIEW

**Comment by antarus** [comment]
Awesome job.

Test and seems OK.

I have a question about the `api/modules` response:
Why not bring up the notion of tree(https://github.com/jhipster/jhipster-lite/issues/1666) and put cucumber "in" springboot with sub category as `tests`?

**Comment by DamnClin** [comment]
> Awesome job.
> 
> Test and seems OK.
> 
> I have a question about the `api/modules` response: Why not bring up the notion of tree(#1666) and put cucumber "in" springboot with sub category as `tests`?

Because I think we need two modes: 
* 1 where you just apply the module you need and that will be used to patch existing projects;
* 1 where you are guided in module applications and that will come later.

For now I'm focusing on the simple modules application, we'll see later for the guided mode

**Comment by antarus** [comment]
Ok that seems like a good approach.

**Comment by pascalgrimaud** [comment]
Merging this as it was tested by @antarus 
Thanks so much

**Comment by pascalgrimaud** [comment]
Adding a bounty here as it's huge work to achieve this
Plz claim it @DamnClin

**Comment by DamnClin** [comment]
Claimed https://opencollective.com/generator-jhipster/expenses/81952

**Pull request merged**
