### PR TITLE
(engine) Activate more checkstyle rules and fix existing code

### PR DESCRIPTION
**Pull request by murdos**

### CODE REVIEW

**Review by renanfranca — APPROVED** [review]
IMO, the more checks there are, the better. Thank you for your work!

**Comment by pascalgrimaud** [comment]
Thanks for your work @murdos 
Anyway, I'm not totally sure about the final class rules, as in JHLite Custom, you won't be able to extend anymore these classes. Right now, no impact for me, but I think it will reduce the possibility to customize.

**Comment by murdos** [comment]
@pascalgrimaud : these classes are already final because they have a private constructor.
The FinalClass rule just makes sure the contract is explicit when it's already impossible to extend the class.

**Comment by pascalgrimaud** [comment]
Oh I see, so I'm fine

**Pull request merged**
