### PR TITLE
Deploy test-jar when releasing

### PR DESCRIPTION
**Pull request by pascalgrimaud**
- related to https://github.com/jhipster/jhipster-lite/issues/3642

With this:

image

For using in the custom jhlite:

```xml
  <dependencies>
    <dependency>
      <artifactId>jhlite</artifactId>
      <version>${jhlite.version}</version>
      <classifier>tests</classifier>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

### CODE REVIEW

**Comment by DamnClin** [comment]
Not totally fixing the issue since this dependency needs to be added to the custom-jhlite module + need a release to deploy this to central

**Comment by pascalgrimaud** [comment]
I édit this PR to not close the ticket

**Comment by pascalgrimaud** [comment]
So if it's ok, I can merge so?

**Comment by DamnClin** [comment]
Yep, looks good, haven't t tested it though...

**Pull request merged**
