### PR TITLE
Add SpringDoc

### PR DESCRIPTION
**Pull request by Bolo89**
Hello,
- Add spring doc : fix https://github.com/jhipster/jhipster-lite/issues/219

Example : 

```json
{
  "folder": "/home/bolo/Projects/my-project-test",
  "generator-jhipster": {
    "projectName": "Beer Project",
    "baseName": "beer",
    "prettierDefaultIndent": 2,
    "packageName": "tech.jhipster.beer"
    "apiTitle": "My API",
    "apiDescription": "My API description",
    "apiLicenseName": "Custom 5.0",
    "apiLicenseUrl": "http://license-url.fr",
    "apiExternalDocDescription": "External API doc description",
    "apiExternalDocUrl": "http://external-api-doc.fr"
  }
}
```

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Huge work @Bolo89 !
Thanks so much, as I'll need this very soon.
I'll do my best to review it today or tomorrow :-)

**Review by pascalgrimaud — CHANGES_REQUESTED** [review]

**Comment by pascalgrimaud** [comment]
Not related to this PR, but we have 2 possible uses cases about Security

1st use case:
- add springdoc
- add Security JWT (or OAuth2 later)
- should do something to springdoc code <---

2nd use case:
- add Security
- add springdoc, we could generate immediatly the security part

Let's do this in another PR, I have some ideas, using Spring Events

**Review by pascalgrimaud — APPROVED** [review]

**Comment by Bolo89** [comment]
Hello,
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/61784

**Comment by pascalgrimaud** [comment]
@Bolo89 : approved! Thanks so much for your 1st contribution

**Pull request merged**
