### PR TITLE
add placeholder during load

### LINKED ISSUE #3005: Rework page loading
Loading pages now just display a "Loading" text which is not good and comes with a blinking effect when changing page, adding placeholder during loading may be a good idea

### PR DESCRIPTION
**Pull request by renanfranca**
Fix #3005

### CODE REVIEW

**Comment by renanfranca** [comment]
I implemented the placeholder loading. I've done my best to maintain the project standards. I used this placeholder loading framework: https://www.npmjs.com/package/placeholder-loading

I appreciate it if someone can review and feedback on this. Thank you in advance! 😄 👍

**Comment by DamnClin** [comment]
@Gnuk is busy for the coming days but he is probably the most suited to review that. On my side I'd prefer if we add that to our pattern library and I think there is not that much work now

**Review by DamnClin — DISMISSED** [review]

**Comment by renanfranca** [comment]
Hello @DamnClin,

I only rebased this pull request to solve the merge conflict by updating it with the main branch.

I saw that you approved these changes. Can it be merged into the main?

Thanks ✌️

**Comment by pascalgrimaud** [comment]
@renanfranca : claim the full bounty and you'll improve this part in another PR

**Comment by renanfranca** [comment]
> @renanfranca : claim the full bounty and you'll improve this part in another PR

Bounty Claimed https://opencollective.com/generator-jhipster/expenses/141575 😄 ✌️ 

Cool 🤝! I'll do the improvements 👍, Thanks 😃 

Thanks @pascalgrimaud and @DamnClin 👏

**Comment by pascalgrimaud** [comment]
@renanfranca : approved

**Pull request merged**
