### PR TITLE
Allcontributors

### LINKED ISSUE #8161: Idea: Use allcontributors.org
Doc: https://allcontributors.org/

Use allcontributors.org to add contributors in README

Command to add contributor in README: `./node_modules/.bin/all-contributors add NEW_GITHUB_CONTRIBUTOR code`

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #8161 

image

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
It's an interesting idea, but should it be updated manually ? As the links are hard coded here

**Comment by qmonmert** [comment]
@pascalgrimaud yes I used this command `./node_modules/.bin/all-contributors add NEW_GITHUB_CONTRIBUTOR code` to add contributors
but there is a bot that we can install https://allcontributors.org/docs/fr/bot/overview to say for example `@all-contributors please add @<username> for <contributions>` https://allcontributors.org/docs/fr/bot/usage

**Comment by pascalgrimaud** [comment]
Give me time to think about it, as I wonder if it's deserved to be displayed in README, because there is already a section for that:
image

For example, when I navigate to other projects, I don't care about the contributors of the project. I only need to have important information in README to know what this project is used for, how I can install it, etc.

**Comment by qmonmert** [comment]
@pascalgrimaud ok no problem, it was an idea, I see that and I found that cool :)

**Comment by qmonmert** [comment]
ok I close

**Pull request closed without merging**
