### PR TITLE
jMolecules and jQAssistant (living) documentation modules

### PR DESCRIPTION
**Pull request by murdos**
https://github.com/xmolecules/jmolecules
https://github.com/jQAssistant

### CODE REVIEW

**Comment by DamnClin** [comment]
So much waiting for this modules! (I'm lucky enough to have seen them in action). @pascalgrimaud  I really think this deserve a Bounty, this is clearly a game changer!

**Comment by murdos** [comment]
I propose to merge this PR.
My initial intent was to also work an applying these living documentation concepts on our sample modules, but since it's a lot of work, I'll do it in an other PR.

**Comment by murdos** [comment]
@pascalgrimaud : bounty claimed: https://opencollective.com/generator-jhipster/expenses/213112

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
