### PR TITLE
Keycloak: remove duplicate entries in jhipster-realm.json.mustache

### LINKED ISSUE #7997: Keycloak: improve jhipster-realm.json.mustache
The key "users" is duplicated in the config

image

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #7997

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
My first idea was to merge all users, to not duplicate the 'users' entry.

Then, I don't know if this user is a default one, provided by Keycloak, or if it was added by JHipster.
If it's provided: we should keep
If not, we should delete as we should not add unused users

**Comment by qmonmert** [comment]
@pascalgrimaud you're right, this user is necessary and it's normal to have two entries in the JSON
On the generator we have also two entries:
https://github.com/jhipster/generator-jhipster/blob/561a0ef2fd8da1c6ba2c653b29e81fd3b4004656/generators/docker/templates/docker/realm-config/jhipster-realm.json.ejs#L502
https://github.com/jhipster/generator-jhipster/blob/561a0ef2fd8da1c6ba2c653b29e81fd3b4004656/generators/docker/templates/docker/realm-config/jhipster-realm.json.ejs#L2587
I think that we can close this PR and the issue

**Comment by pascalgrimaud** [comment]
Because the file from generator-jhipster is not a good one, and it's my fault because I copy from there.
That's why I created the ticket to improve it and to remove old and deprecated stuff

**Comment by qmonmert** [comment]
@pascalgrimaud ok
I tried to start Keycloak without this user and all seems good
I think that is is not provided by Keycloak but I'm not a specialist of Keycloak :)

**Comment by pascalgrimaud** [comment]
That's why I think this file must be reworked completely, using this workflow:
- start a fresh Keycloak without any custom
- add manually what it is needed by a generated JHLite project
- then export the settings (realm, user, etc)

The scope of this PR should be to move the custom users (admin + user), near to `service-account-internal`
The `service-account-internal` should not be removed, as I think it's an internal user of Keycloak

**Comment by qmonmert** [comment]
@pascalgrimaud this is what I tried yesterday, I created a new realm but I struggle to retrieve users ...

**Comment by pascalgrimaud** [comment]
Thanks and no worry, I created this ticket and I know exactly what to do to have a clean json file to import when starting Keycloak

As for my customer, we just upgraded to Keycloak 22 :-)

**Comment by qmonmert** [comment]
ok 🙂

**Comment by pascalgrimaud** [comment]
closing in favor of https://github.com/jhipster/jhipster-lite/pull/8148

**Pull request closed without merging**
