### PR TITLE
define preset json file name at spring boot application config

### LINKED ISSUE #10553: preset.json in spring config
See https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/project/infrastructure/secondary/FileSystemProjectsRepository.java#L29

Instead of hard coding this file, it should be nice to allow this as config in spring properties

Several use cases:
- in jhlite extension, we could use specific presets
- in spring profile vue, we could have vue instead of angular
- etc

### PR DESCRIPTION
**Pull request by renanfranca**
Fix #10553

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
just did a new release, but it doesn't work, so I broke the preset feature :(

**Comment by pascalgrimaud** [comment]
I'm going to revert it and doing a new patch release for having the preset feature

**Comment by renanfranca** [comment]
> just did a new release, but it doesn't work, so I broke the preset feature :(

Did that PR  broke it?

**Comment by pascalgrimaud** [comment]
yes, the preset.json is not found

**Comment by renanfranca** [comment]
> Yes, the preset.json is not found

Later or on Monday, I will take a look at it. I didn't delete the branch 👍👌

**Comment by renanfranca** [comment]
> yes, the preset.json is not found

Fixed it here https://github.com/jhipster/jhipster-lite/pull/10590

**Pull request merged**
