### PR TITLE
Gateway module

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2117

### CODE REVIEW

**Comment by antarus** [comment]
seems good. Unfortunately I can't test it today.

**Comment by DamnClin** [comment]
> seems good. Unfortunately I can't test it today.

We spot a very probable mistake in the existing module with @pascalgrimaud in the bootsrap properties management (that were on yaml style in a properties file). This version is supposed to be better BUT I have no idea of what those properties were doing (and don't really want to take a deep look at it). @pascalgrimaud can test that easily on is current project I think :)

**Comment by pascalgrimaud** [comment]
Yes, I'll review and test it very soon

**Comment by pascalgrimaud** [comment]
Just tested it at and it works well:

image

The API too http://localhost:8080/api/gateway/routes

But we need to ignore these logs to logback, otherwise, we are spammed in the console :D

```xml
  <logger name="org.apache" level="ERROR" />
  <logger name="reactor.netty" level="ERROR" />
  <logger name="io.netty" level="ERROR" />
```

**Comment by pascalgrimaud** [comment]
Can you resolve the conflict plz @DamnClin so it can be merged

**Pull request merged**
