### PR TITLE
Fix: Update apache/kafka-native Docker tag to v3.9.0

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #11313

@pascalgrimaud @murdos I opend an issue https://github.com/testcontainers/testcontainers-java/issues/9506 on tescontainers.
I use temporary fix proposed on the ticket.

### CODE REVIEW

**Comment by murdos** [comment]
Thanks for raising the issue on testcontainers side.

I'd rather wait for the fix/official support from testcontainers. I don't think we're in a hurry to make the upgrade, but that's just my opinion.

**Comment by qmonmert** [comment]
@murdos ok

@pascalgrimaud merge or wait? 🙂

**Comment by pascalgrimaud** [comment]
In fact, I'm not sure it's an issue.
Maybe the proposed fix is what we should do, as our generated kafka.yml already have this property:

image

**Comment by qmonmert** [comment]
@pascalgrimaud I believe that `kafkaContainer = new KafkaContainer(DockerImageName.parse("apache/kafka-native:3.9.0")).withNetwork(null);` not used `kafka.yml` to start, so updating this file won't change behavior

**Comment by pascalgrimaud** [comment]
Yes I know, I wanted to say your suggestion would be consistent with the generated kafka.yml file

**Comment by pascalgrimaud** [comment]
I'm merging this, so the upgrade to the v3.9.0 Docker image can be done, until there is a v3.9.1 with an eventual fix

**Comment by qmonmert** [comment]
👍

**Pull request merged**
