### PR TITLE
Add React

### PR DESCRIPTION
**Pull request by qmonmert**
Related to https://github.com/jhipster/jhipster-lite/issues/293

You can do:
- POST /api/projects/init
- POST /api/react
- npm i
- npm start

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@qmonmert : thanks for this PR

Just be patient, this friday, we'll have our JHipster Day, so we'll be able to review this PR and the Angular one.
So we will provide some feedbacks

**Comment by pascalgrimaud** [comment]
Another thing, you should give a try to "vite" and test it: `npm init vite@latest vitereact`

**Comment by pascalgrimaud** [comment]
@qmonmert : I'm closing this, in favor of https://github.com/jhipster/jhipster-lite/pull/733 which contains your 2 commits and initial work.
We'll see how the bounty can be shared or increased, once the work is finished and merged

**Comment by qmonmert** [comment]
@pascalgrimaud ok no problem

**Pull request closed without merging**
