### PR TITLE
Startup commands improvements

### PR DESCRIPTION
**Pull request by murdos**

### CODE REVIEW

**Comment by renanfranca** [comment]
Thanks, Interesting improvements! I am going to take a closer look as it is an opportunity to learn 😊

**Review by renanfranca — APPROVED** [review]
@murdos : Thank you very much! 💙


This new switch features makes me want to use the interfaces instead of enums. There was a lot of stuffs going on at the interface StartupCommand:
-  including the supresswarning because it's in different records
- more than one "public" records in the same file which makes sense for me, but sometimes it isn't considere best practices by my co-works

I am going to use this approach at my next issue #8963 !

**Comment by murdos** [comment]
@renanfranca : thanks for the feedback! I've moved all implementations of StartupCommand to their own top-level file :)

**Comment by renanfranca** [comment]
> I've

Nice! You are welcome 👍😁

**Pull request merged**
