### PR TITLE
Put landscape in light

### PR DESCRIPTION
**Pull request by Gnuk**
This PR put landscape in light style, it's a step to have less coupling on font and colors during the migration to Tikui.

* Preparation for #3970 
* Related to #2894

### CODE REVIEW

**Comment by Gnuk** [comment]
Maybe @DamnClin and @pascalgrimaud, you may see if all colors still visible for each cases.

**Comment by pascalgrimaud** [comment]
Can you add a little screenshot plz?

**Comment by Gnuk** [comment]
Here is a screen:

Screenshot_20221024_163300

**Comment by DamnClin** [comment]
All visible but the grey looks more active than the white to me so I have a strange feeling :D (and it's very white....)

**Comment by pascalgrimaud** [comment]
LGTM, can it be merged, @Gnuk @DamnClin ?

**Comment by DamnClin** [comment]
> LGTM, can it be merged, @Gnuk @DamnClin ?

Ok for me

**Comment by Gnuk** [comment]
It's ok, we will change it later using the chip I imagine cc @nassimerrahoui  on #4089 and later :p

**Pull request merged**
