### PR TITLE
feature(custom-jhlite): setup custom npm and maven version reader to handle custom npm/java dependencies

### LINKED ISSUE #10850: custom-jhlite should generate necessary material for handling custom java dependencies
When writing custom modules in a custom-jhlite instance, you'll probably need to declare new java dependencies, maven and/or gradle plugins.

In order to ease that, custom-jhlite should generate an empty pom.xml in the resources folder (and similar files for gradle), and what's needed for reading the dependencies they contain.

### LINKED ISSUE #10851: custom-jhlite should generate necessary material for handling custom npm dependencies
Similar to #10850, when writing custom modules in a custom-jhlite instance, you'll probably need to declare new npm dependencies.

In order to ease that, custom-jhlite should generate an empty package.json in the resources folder, and what's needed for reading the dependencies it contains.

Requires #10852

### PR DESCRIPTION
**Pull request by murdos**
Fixes #10850 and fixes #10851

### CODE REVIEW

**Comment by murdos** [comment]
FYI I've updated https://github.com/jhipster/jhipster-lite-extension/pull/85 that shows the purpose of this PR.
The first commit (https://github.com/jhipster/jhipster-lite-extension/pull/85/commits/f0653240da81d8b7324f55ce2a5aeb51664a9233) corresponds to the application of the changes of the custom-jhlite module made in this PR.

**Review by renanfranca — APPROVED** [review]
Thank you for your work once again, @murdos! I am used to this pattern of having different commits for features and implementation. It's so hard to review everything in a single commit 😅

**Comment by murdos** [comment]
Thanks for the reviews @renanfranca, it's really appreciated! 👍

**Comment by renanfranca** [comment]
> Thanks for the reviews @renanfranca, it's really appreciated! 👍

You're welcome 😊

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
