### PR TITLE
Feature/issue 5324 cassandra dummy

### LINKED ISSUE #5324: Cassandra: dummy module
Following #877 and https://github.com/jhipster/jhipster-lite/issues/5181

### PR DESCRIPTION
**Pull request by Yourgene**
Fixes #5324

Notes:
- When launching tests in generated project, these WARN are displayed : `You have too many session instances: 6 active, expected less than 4 (see 'advanced.session-leak.threshold' in the configuration)`. This is "normal", Spring creates and caches an ApplicationContext everytime a new one is needed. In this project, 6 different ApplicationsContexts are created and cached, and their cassandra sessions remain active; throwing this message when more than 4 are detected.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@Yourgene : is this PR ready to be reviewed ?

**Comment by Yourgene** [comment]
Yes!

**Review by DamnClin — APPROVED** [review]

**Comment by DamnClin** [comment]
LGTM, as it is a feature with a Bounty I'll let @pascalgrimaud merge it :)

**Comment by pascalgrimaud** [comment]
I'm so sorry, too buzy these last weeks, not enough time to have a close look
So trusting you, thanks @DamnClin and @Yourgene

**Comment by Yourgene** [comment]
Hi, I submitted the bounty [here](https://opencollective.com/generator-jhipster/expenses/128122)

**Comment by pascalgrimaud** [comment]
@Yourgene : approved

**Pull request merged**
