### PR TITLE
[Java] Replace with single class imports

### PR DESCRIPTION
**Pull request by qmonmert**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@qmonmert : don't understand, why doing this?

**Comment by qmonmert** [comment]
@pascalgrimaud 
image

but no problem if you prefer not merging :)

**Comment by pascalgrimaud** [comment]
Interesting. Can you provide the original link of this text plz? I'd like to read it

**Comment by qmonmert** [comment]
@pascalgrimaud https://jiga.dev/avoiding-wildcard-imports-in-java-kotlin-with-intellij/

**Comment by pascalgrimaud** [comment]
Fine, let's merge this.
I need to customize my intellij for this, maybe we could add a section in contributing about this part too

**Review by pascalgrimaud — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
Just to know, how did you do this @qmonmert ? By hand (file by file) or do you have a tool?

**Comment by qmonmert** [comment]
@pascalgrimaud I did file by file 😅 I was thinking that it will be fast but no ^^

**Comment by qmonmert** [comment]
on each file, I click on the popup to refacto

**Comment by pascalgrimaud** [comment]
Thanks a lot for your work. I'm adding a bounty for this

**Comment by qmonmert** [comment]
oh thanks @pascalgrimaud 🙂

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/70831 :)

**Comment by pascalgrimaud** [comment]
@qmonmert : approved :)

**Pull request merged**
