### PR TITLE
Docker images: improve the JVM image & create a native image

### PR DESCRIPTION
**Pull request by jdubois**
This is building on what I've done for Nubesgen.com and the goal is to deploy easily and very cheaply to Azure Container Apps (for NubesGen I'm paying less than $4 this month, and I have a minimum of 1 hot instance!!)

### CODE REVIEW

**Comment by jdubois** [comment]
With the native image build, I'm still getting a JGit error: @atomfrede @pascalgrimaud I see you have added a number of hints in `tech.jhipster.lite.module.infrastructure.secondary.git.NativeHints` so it seems you have already worked on this, is this supposed to be working already?

My error is when I apply a module, I get:

```
2023-04-28 22:24:05 2023-04-28T20:24:05.687Z  INFO 1 --- [nio-7471-exec-6] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-28 22:24:11 Exception in thread "Thread-3" org.eclipse.jgit.errors.TranslationBundleLoadingException: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en]
2023-04-28 22:24:11     at org.eclipse.jgit.nls.TranslationBundle.load(TranslationBundle.java:141)
2023-04-28 22:24:11     at org.eclipse.jgit.nls.GlobalBundleCache.lookupBundle(GlobalBundleCache.java:64)
2023-04-28 22:24:11     at org.eclipse.jgit.nls.NLS.get(NLS.java:125)
2023-04-28 22:24:11     at org.eclipse.jgit.nls.NLS.getBundleFor(NLS.java:101)
2023-04-28 22:24:11     at org.eclipse.jgit.internal.JGitText.get(JGitText.java:28)
2023-04-28 22:24:11     at org.eclipse.jgit.util.FS$GobblerThread.setError(FS.java:1504)
2023-04-28 22:24:11     at org.eclipse.jgit.util.FS$GobblerThread.run(FS.java:1474)
2023-04-28 22:24:11     at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
2023-04-28 22:24:11     at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
2023-04-28 22:24:11 Caused by: java.util.MissingResourceException: Can't find bundle for base name org.eclipse.jgit.internal.JGitText, locale en
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.getBundle(ResourceBundle.java:1280)
2023-04-28 22:24:11     at org.eclipse.jgit.nls.TranslationBundle.load(TranslationBundle.java:138)
2023-04-28 22:24:11     ... 8 more
2023-04-28 22:24:11 Caused by: java.lang.ClassCastException: org.eclipse.jgit.internal.JGitText cannot be cast to ResourceBundle
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
2023-04-28 22:24:11     at java.base@17.0.7/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
2023-04-28 22:24:11     ... 11 more
```

If you want to reproduce: `docker build . -f Dockerfile.native -t jhipster/jhipster-lite-native` on this branch, and then you need to run the image.

**Comment by pascalgrimaud** [comment]
As far as I can remember, I couldn't get the GraalVM + Docker image to work.
Only the native JAR using GraalVM, so waiting @atomfrede's answer :)

**Comment by jdubois** [comment]
Oh outside of this issue, it’s all running fine, you should give it a try, it’s impressive!
If JGit is to much an issue, I’ll switch to using the local git client.

**Comment by pascalgrimaud** [comment]
sure, I'll give a try :)

**Comment by atomfrede** [comment]
Need to check but I usually used the native image. What locale is your os?

**Comment by jdubois** [comment]
This is running inside my Docker container, so this would be the default for Ubuntu (probably "en").
I believe localisation bundles for JGit aren’t being included by GraalVM.

**Comment by atomfrede** [comment]
Will have a look how to integrate the resource bundles. Seems like an additional configuration

**Comment by jdubois** [comment]
Thanks @atomfrede ! I won’t touch this for 1 week, then!

**Comment by atomfrede** [comment]
Is the native image build as described in the readme working for you with the changes? (Just on my mobile so can check right now)

**Comment by jdubois** [comment]
You need to use those from this branch.
The Dockerfile is a Java-based image that should be all good.
The Dockerfile.native is the native image that works fine except when you apply a module, as this uses JGit.

**Comment by atomfrede** [comment]
I think I have an idea what the problem is (I think I have seen a similar issue without native images and different locale). jgit seems not to contain bundles for every language. Thinking of at build time the locale is different compared to runtime which results in this behaviour. Will try later and keep you updated.

**Comment by jdubois** [comment]
Thanks! I see your commits and you seem on the right solution @atomfrede !

**Comment by atomfrede** [comment]
@jdubois Will try to rebase your branch on main tonight to see if it works now

**Comment by jdubois** [comment]
Very cool @atomfrede ! Otherwise we should shift to using native Git, at least we know it will work.

**Comment by atomfrede** [comment]
I tried your branch and sadly it seems not to work. I have no error in the ui (compared to the state on main before) but I see the same error with the resource bundle, but only one time.
Maybe it has something todo with the layer image bundling and not building a fat jar such that the resource bundle really can't be found in the package? 
I guess it will work flawlessly when we provide the resource bundle ourselfs.

**Comment by atomfrede** [comment]
Just double checked main again, doing
```
./mvnw clean native:compile -Pnative -DskipTests
./target/jhlite
```
works fine without the error. So it seems to have something to do with the docker packing (or layered packing) in your branch. Will try to investigate a little more if I can pin point the problem a little more.

**Comment by jdubois** [comment]
Oh at least this is giving some good hope it can work, thanks !
I’ll have more time in 1-2 weeks to test also myself.

**Comment by jdubois** [comment]
Yes I was having the error in the UI, and the stacktrace.

**Pull request closed without merging**
