### PR TITLE
add develocity integration

### PR DESCRIPTION
**Pull request by atomfrede**
This PR adds leverages our own [gradle develocity ](https://ge.jhipster.tech/) to have build scans and build cache support for CI/CD and on local developer machines. @jdubois already added the needed secret to have write access from our github runners to gradle develocity. Anyone can read from the remote cache and of course use the local build cache. 

If you would like to know more about develocity or would like to have an own user account just give me a ping.

We should squash the commits :)

### CODE REVIEW

**Review by murdos — APPROVED** [review]

**Comment by murdos** [comment]
@atomfrede : Awesome! 
What can you do with your own user account?

**Comment by atomfrede** [comment]
An account gives you permission to write also to the build cache, api access (which I only needed for the gradle develocity experiments during on boarding) and you can e.g. purge/clear the build cache. All other things, like using the build cache, analyzing builds can be done anonymous.

**Comment by pascalgrimaud** [comment]
We need to be sure it will work for JHLite Custom and in private enterprise

**Comment by atomfrede** [comment]
You mean if someone clones the repo and uses it internally? I think there won't be issues as the develocity plugin steps down gracefully when e.g. firewall or so blocks it. Or we just make it opt in and enable it for our ci for example

**Comment by atomfrede** [comment]
Can we somehow reliable test it?

**Comment by pascalgrimaud** [comment]
@murdos would be able to test it after his holidays, as he built a JHLite Custom for his customer :)

**Comment by murdos** [comment]
I tested it quickly in private enterprise, and I've not encountered any issues 🙂

**Pull request merged**
