### PR TITLE
Setup new triage labeling

### PR DESCRIPTION
**Pull request by renanfranca**
See
- https://github.com/jhipster/jhipster-lite/issues/8528#issuecomment-1919049105

### CODE REVIEW

**Comment by murdos** [comment]
Previous workflow was not adding `triage` label if there were already some labels: does it work the same way?

**Comment by renanfranca** [comment]
> Previous workflow was not adding `triage` label if there were already some labels: does it work the same way?

I have to study the configuration options with regular expressions. Today it applies if there are some labels: https://github.com/renanfranca/test-issue-label-github-action/issues/9
image

By the way, thanks for approving the pull request (https://github.com/github/issue-labeler/pull/82), that was unexpected! Cool! 😎  Do you have write access there too?

**Comment by pascalgrimaud** [comment]
Yes the rules are:
- if no label, add triage
- if existing label, do nothing

**Comment by pascalgrimaud** [comment]
@renanfranca : everyone can approved pull request, you don't need to have permission

**Comment by renanfranca** [comment]
I prefer to add one more step to check if there are any labels rather than implement the changes inside the github-action issue-labeler itself. I think issue-laber is better generic than specialized in everyone's needs.

It is working for issues:

- labeling when there is no label (https://github.com/renanfranca/test-issue-label-github-action/issues/23)
image

- not labeling when already labeled (https://github.com/renanfranca/test-issue-label-github-action/issues/24)
image

It is working for pull requests:

- labeling when there is no label (https://github.com/renanfranca/test-issue-label-github-action/pull/25)
image

- not labeling when already labeled (https://github.com/renanfranca/test-issue-label-github-action/pull/26)
image

**Comment by pascalgrimaud** [comment]
Totally agree. It's specific to here, that's why the code belong to this repo
Thanks @renanfranca for your work

**Comment by renanfranca** [comment]
@pascalgrimaud : You are welcome! 😃👍

**Pull request merged**
