### PR TITLE
Rename cypress module

### PR DESCRIPTION
**Pull request by DamnClin**

### CODE REVIEW

**Comment by nonomoho** [comment]
Change in front too?

**Comment by DamnClin** [comment]
> Change in front too?

What do you mean?

**Comment by nonomoho** [comment]
You have `REACT_CYPRESS = 'REACT_CYPRESS',` in Service.ts for instance

**Comment by DamnClin** [comment]
I think this is useless and should be deleted :)

**Comment by DamnClin** [comment]
https://github.com/jhipster/jhipster-lite/pull/2803 :)

**Review by nonomoho — APPROVED** [review]

**Pull request merged**
