### PR TITLE
bump Vue 3.4.19

### PR DESCRIPTION
**Pull request by qmonmert**

### CODE REVIEW

**Comment by murdos** [comment]
I don't understand why you're doing the version bump manually instead of letting dependabot doing it automatically.

**Comment by qmonmert** [comment]
@murdos because the version is not updated since `3.4.13` 

that's why...

image

**Comment by qmonmert** [comment]
and sometimes it's interesting to watch the version bump (ex: #9004 ) ....

**Comment by murdos** [comment]
> @murdos because the version is not updated since `3.4.13`
> 
Hmm... what would be interesting is to investigate why it's not updated automatically :/

**Comment by qmonmert** [comment]
at least I noticed it!

so this PR is not "interesting" ... you can close this PR if you want and find a better solution ...

**Comment by murdos** [comment]
Closing in favor of #9009: we'll then see if dependabot is able to update vuejs automatically.

**Comment by murdos** [comment]
@renanfranca : I did not succeed in founding the root cause of dependabot not doing the update. I've opened #9030 to track the issue for future vuejs releases, and I propose to manually update vuejs version with your PR :+1:

**Comment by qmonmert** [comment]
@murdos ok I update this PR

**Comment by murdos** [comment]
@qmonmert : Thanks!

**Pull request merged**
