### PR TITLE
Fix Arch tests on windows

### LINKED ISSUE #302: CI with Windows

### PR DESCRIPTION
**Pull request by MSaguer**
To partialy fix #302 

Fix HexagonalArch test on Windows

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@MSaguer : just merged this PR https://github.com/jhipster/jhipster-lite/pull/509 which contains this fix. After update, can you test the latest 'main' branch and tell me if everything works fine on your side plz ?

**Comment by MSaguer** [comment]
I didn't see that !504 already did the job. I close this

**Comment by MSaguer** [comment]
@pascalgrimaud all tests running on windows are Ok on main branches.

**Comment by pascalgrimaud** [comment]
Thanks for your feedbacks @MSaguer ! Nice to know it works better on Windows machine

**Pull request closed without merging**
