### PR TITLE
Adding workflow dispatch in release drafter

### PR DESCRIPTION
**Pull request by Saravana-PS**
@pascalgrimaud Added workflow dispatch in release drafter. fix https://github.com/jhipster/jhipster-lite/issues/7089

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@Saravana-PS : thanks. Small tips: can you add `fix https://github.com/jhipster/jhipster-lite/issues/7089` to your description here plz? So the ticket will be closed automatically once the PR is merged

**Comment by Saravana-PS** [comment]
> @Saravana-PS : thanks. Small tips: can you add `fix https://github.com/jhipster/jhipster-lite/issues/7089` to your description here plz? So the ticket will be closed automatically once the PR is merged

@pascalgrimaud Do you want me to add this in the pull request description or in the issue description?

**Comment by pascalgrimaud** [comment]
In the description of the pull request, something here:

image

**Comment by Saravana-PS** [comment]
@pascalgrimaud Thanks for the valuable input as always.

**Review by pascalgrimaud — APPROVED** [review]

**Pull request merged**
