### PR TITLE
Bump model-maven-helper to version 35

### PR DESCRIPTION
**Pull request by murdos**

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud maybe you can add a bounty on this, because we are working with @murdos and the main contributor of the lib 🙂

**Comment by pascalgrimaud** [comment]
Done, if it's more work, I can add more

**Comment by qmonmert** [comment]
thanks @pascalgrimaud

**Review by qmonmert — APPROVED** [review]

**Comment by qmonmert** [comment]
@murdos for the bounty 100 for you 100 for me?

**Comment by murdos** [comment]
@qmonmert : I thought the bounty would be for @gastaldi, he is the one having done the hard work.

**Comment by pascalgrimaud** [comment]
Easier to share now :)

**Comment by murdos** [comment]
Thanks @pascalgrimaud !
@gastaldi Here's the doc for the bounty: https://www.jhipster.tech/bug-bounties/#-bug-bounties 😉

**Comment by gastaldi** [comment]
@murdos thank you! I've submitted an expense stating `$100 bug bounty claim for https://github.com/jhipster/jhipster-lite/pull/9270`.

**Comment by qmonmert** [comment]
thanks @pascalgrimaud https://opencollective.com/generator-jhipster/expenses/194808

**Comment by murdos** [comment]
https://opencollective.com/generator-jhipster/expenses/194847 :-)

**Comment by pascalgrimaud** [comment]
@gastaldi @qmonmert @murdos : approved. Thanks for this team work, guys!

**Pull request merged**
