### PR TITLE
Fix: bump org.testcontainers:mongodb from 1.19.1 to 1.19.2

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #8050 

⚠️  Not sure if it is the best solution

### CODE REVIEW

**Comment by murdos** [comment]
That's strange. I'll investigate what has changed on testcontainter side.

**Comment by qmonmert** [comment]
thanks @murdos

**Comment by murdos** [comment]
Better fix proposed here: https://github.com/jhipster/jhipster-lite/pull/8070

**Comment by pascalgrimaud** [comment]
Thanks @qmonmert and @murdos 
You're both awesome :-)

I'm closing this one as the other seems better indeed

**Pull request closed without merging**
