### PR TITLE
Skip ci with keywords at head commit message or pull request title

### PR DESCRIPTION
**Pull request by renanfranca**
See
- https://github.com/jhipster/jhipster-lite/issues/1627#issuecomment-1912109856

### CODE REVIEW

**Comment by renanfranca** [comment]
@pascalgrimaud : here is the change proposal for ignoring the ci. I saw that the `tests-windows` don't have the if needed to ignore the job, so I kept it that way.

I am looking for an alternative to use the [ci skip] and [skip ci] keywords which is more elegant: https://stackoverflow.com/questions/76103981/how-can-i-override-github-actions-or-cloud-build-skip-ci

**Comment by renanfranca** [comment]
I am going to check that bug at my fork:
image

**Comment by renanfranca** [comment]
> I am going to check that bug at my fork: image

It is fixed: must remove commit line breaks.

**Comment by pascalgrimaud** [comment]
thanks @renanfranca : let's give it a try :)

**Pull request merged**
