### PR TITLE
bump io.mongock:mongock-bom from 5.4.2 to 5.4.3

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #10038

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud @murdos not sure if it is the best solution, WDYT?

**Comment by qmonmert** [comment]
I did the same thing on the generator https://github.com/jhipster/generator-jhipster/pull/26409 and it was merged

**Comment by pascalgrimaud** [comment]
Just if you can find the doc to know what this property is used for

**Comment by qmonmert** [comment]
@pascalgrimaud https://docs.mongock.io/v5/features/transactions/index.html

image

**Comment by murdos** [comment]
FYI The breaking change will be reverted in an upcoming 5.4.4 version.

**Pull request closed without merging**
