### PR TITLE
Introduce annotation @ExcludeFromGeneratedCodeCoverage

### PR DESCRIPTION
**Pull request by murdos**
This annotation will also be detected by Jacoco since it contains "Generated". 
Uses this new annotation in replacement of `@Generated` in places where it was explicitly added to skip code coverage check.

Having code annotated with `@Generated(reason = "Hard to test implement detail error management")` is a bit weird and misleading, since the code has not been generated, but written manually. And the reason is not here to explain why the code has (not!) been generated, but why we want to exclude it from code coverage report.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Maybe a shorter name like 'ExcludeFromCoverage' ?
Let's propose others before changing :-)

**Comment by DamnClin** [comment]
> Unless it must absolutely contain Generated

It must (unless some change were made on Jacoco on that)

**Comment by pascalgrimaud** [comment]
@murdos : what do you think about doing the same for the generated part?

**Comment by murdos** [comment]
> @murdos : what do you think about doing the same for the generated part?

I was planning to do that too, but was waiting for the feedback on the generator :-) 
I'll do that soon.

**Pull request merged**
