### PR TITLE
group oauth2 modules under the same feature

### LINKED ISSUE #4313: Add feature for spring boot oauth2 providers
The spring boot oauth2 modules for providers should be in the same feature:

* `spring-boot-oauth2-auth0`
* `spring-boot-oauth2-okta`

### PR DESCRIPTION
**Pull request by Yourgene**
Fixes #4313

I didn't find any relevant test cases to edit/create.

If there's some, please let me know and I will update the PR.

### CODE REVIEW

**Comment by DamnClin** [comment]
> I didn't find any relevant test cases to edit/create

This is configuration, not tested :⁠-⁠)

**Comment by Yourgene** [comment]
> This is configuration, not tested :⁠-⁠)
Perfect then !

Can you explain why features and dependencies are considered as configuration and not domain ? 

Instinctively, I would say that knowing module's dependencies is as important as knowing module's  properties (for example, `auth0ClientId` for auth0), and thus dependencies should have their place in ModuleFactories.

I would be happy if you can enlighten me on where I'm wrong in my previous statement.

**Comment by DamnClin** [comment]
> Can you explain why features and dependencies are considered as configuration and not domain ?

In fact it was be cool to test it but not just by ensuring that it has the configuration we want in test since this brings nothing. It would be cool to test all possible application génération (there are some issues going that way) but we already have a combination explosion problem :⁠-⁠)

**Comment by DamnClin** [comment]
Congratulation for your first contribution!

**Comment by DamnClin** [comment]
> Don't you want me to group the springdoc modules in this merge ?

As you want, same for me :D (struggling with a lot of build and not enough fire power to build them for now, this is probably the reason for you build fail :D)

**Comment by Yourgene** [comment]
> As you want, same for me :D (struggling with a lot of build and not enough fire power to build them for now, this is probably the reason for you build fail :D)

Let's do it then:) I will update the PR in the next hour.

> this is probably the reason for you build fail :D
yes, the error is unrelated to the part I worked on

**Comment by Yourgene** [comment]
ahah, too late

**Comment by DamnClin** [comment]
Damnit... sorry, this is something really strange, dunno why failling build keep getting merged when enabling auto merge when build suceed... (forgot to disable it)

**Comment by Yourgene** [comment]
no worries !

we can do it later in a new issue

**Pull request merged**
