### PR TITLE
Remove bootstrap

### LINKED ISSUE #2834: Remove bootstrap
Bootstrap is not really needed anymore, we can remove it (but need to rework header and replace icons. cc @nonomoho I know you have started somethings on that

### PR DESCRIPTION
**Pull request by Gnuk**
* Linked to #2894
* Resolves #2834

### CODE REVIEW

**Comment by DamnClin** [comment]
Some bootrstrap css classes in `Toast.vue`

**Comment by Gnuk** [comment]
> Some bootrstrap css classes in `Toast.vue`

I've already noticed this, so it's good for me but thank you for the reminder. I'lll start it just after ;)

**Comment by DamnClin** [comment]
Do you plan to take care of https://github.com/jhipster/jhipster-lite/issues/3372 here?

**Comment by Gnuk** [comment]
> Do you plan to take care of #3372 here?

I can but where do you want to see the area?

**Comment by DamnClin** [comment]
>  I can but where do you want to see the area?

No idea, this needs some trys...

**Comment by Gnuk** [comment]
Currently i've added the Toast is a simple version. But cause we're not using Bootstrap anymore I have not implemented the timeout system yet.

@DamnClin : Is it possible to code it in another PR?

(currently, to close the Toast, you have to click on close button)

**Comment by DamnClin** [comment]
The described behavior is ok me but I haven't read the PR nor tried it so can't validate for now :D. @pascalgrimaud can you review that?

**Pull request merged**
