### PR TITLE
Testcontainer mysql: use get version, managed by dependabot

### PR DESCRIPTION
**Pull request by DanielFran**
- related to https://github.com/jhipster/jhipster-lite/issues/615

### CODE REVIEW

**Review by pascalgrimaud — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
@DanielFran : there are some Sonar code smells after this merge. Can you have a look plz? Otherwise, I'll do it later

**Comment by DanielFran** [comment]
@pascalgrimaud In fact the code was already duplicated between Mysql and Postgresql, do not know why only now this is reported. We can move the code to a Generic database class maybe?

**Comment by pascalgrimaud** [comment]
Yes, there is this ticket https://github.com/jhipster/jhipster-lite/issues/419
I can take care of it, as I know how to do

**Comment by DanielFran** [comment]
I cannot work on this until Friday probably, so it is up to you to start this refractor before if you have time... otherwise I can look at it on Friday.

**Comment by pascalgrimaud** [comment]
@DanielFran : it's ok, the code smells have been fixed :)

**Pull request merged**
