### PR TITLE
(frontend-maven-plugin) Install node in target directory

### PR DESCRIPTION
**Pull request by murdos**
As done by generator-jhipster: this avoid an additional top-level directory in project

### CODE REVIEW

**Comment by renanfranca** [comment]
I am not a front-end expert.  But if node_module is installed at target folder, every time. \mvnw clean verify or .\mvnw clean verify sonar:sonar the node_module is going to be delete. So it's going to install everything every time, is that a problem?

**Comment by murdos** [comment]
@renanfranca : this configuration affects `node` directory, not `node_modules` directory. It's the folder where node (and npm) executable is downloaded. The result of `npm install` is still in the `node_modules` at the root of the project.

Also node and npm executable are not downloaded again each time you do a `mvn clean`, they're just unpacked from local maven repository: 
```
[INFO] --- frontend:1.15.0:install-node-and-npm (install-node-and-npm) @ jhlite ---
[INFO] Installing node version v20.11.1
[INFO] Unpacking /home/runner/.m2/repository/com/github/eirslett/node/20.11.1/node-20.11.1-linux-x64.tar.gz into /home/runner/work/jhipster-lite/jhipster-lite/target/node/tmp
```

**Comment by renanfranca** [comment]
> @renanfranca : this configuration affects `node` directory, not `node_modules` directory. It's the folder where node (and npm) executable is downloaded. The result of `npm install` is still in the `node_modules` at the root of the project.
> 
> Also node and npm executable are not downloaded again each time you do a `mvn clean`, they're just unpacked from local maven repository: 
> ```
> [INFO] --- frontend:1.15.0:install-node-and-npm (install-node-and-npm) @ jhlite ---
> [INFO] Installing node version v20.11.1
> [INFO] Unpacking /home/runner/.m2/repository/com/github/eirslett/node/20.11.1/node-20.11.1-linux-x64.tar.gz into /home/runner/work/jhipster-lite/jhipster-lite/target/node/tmp
> ```

Thank you for the explanation 👍

**Review by renanfranca — APPROVED** [review]
Thank you for your work 😊👍

**Pull request merged**
