### PR TITLE
Modules screen

### PR DESCRIPTION
**Pull request by DamnClin**
Related to https://github.com/jhipster/jhipster-lite/issues/1565

So this is a very very simple (and ugly) implementation of the module application screen, lots of UX element are probably missing but this is usable

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Very impressive! Thanks a lot!

**Comment by DamnClin** [comment]
> Very impressive! Thanks a lot!

NP :D I want to add some component test using cypress on that because the vue test utils test are not really testing anything...

**Comment by pascalgrimaud** [comment]
I'm adding a specific bounty for this, as it's well deserved (you can claim it when it's merged)

Yes, about Cypress, indeed, we didn't add real tests so this part should be improved

**Comment by pascalgrimaud** [comment]
you claim it a little bit too early but it's fine, I'm merging this :)

**Comment by DamnClin** [comment]
> you claim it a little bit too early but it's fine, I'm merging this :)

Oh sorry, read too fast... (was drinking coffee)

**Pull request merged**
