### PR TITLE
tmp: introduce code smells

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by zhyd1997** [comment]
Hi @pascalgrimaud 

Sorry for the last PR, too late reply to you.

you can see the changes in this PR: https://github.com/zhyd1997/jhipster-lite/pull/4/files

**Ignore `src` folder changes**.

**Comment by pascalgrimaud** [comment]
> Hi @pascalgrimaud
> 
> Sorry for the last PR, too late reply to you.
> 
> you can see the changes in this PR: https://github.com/zhyd1997/jhipster-lite/pull/4/files
> 
> **Ignore `src` folder changes**.

Sorry,  I don't understand your comment and your last changes :-D
It contains 34 commits, which are related to CSS.

**Comment by zhyd1997** [comment]
See changes in red rectangle part:

Screenshot 2023-05-02 at 15 23 51

You can copy `build.yml` file from SonarCloud to avoid errors.

**Comment by pascalgrimaud** [comment]
Something wrong at Sonarcloud:
- the analysis in main branch was replaced by another one: https://sonarcloud.io/summary/overall?id=jhipster_jhipster-lite
- the 2 pull requests are here, but with false positive: https://sonarcloud.io/project/pull_requests_list?id=jhipster_jhipster-lite

@zhyd1997 : with your change, we can't run local Sonar analysis with additional custom arguments, that's the problem

**Comment by zhyd1997** [comment]
@pascalgrimaud 

Let me submit a PR!

**Comment by pascalgrimaud** [comment]
@zhyd1997 : I created this ticket to follow the issue -> https://github.com/jhipster/jhipster-lite/issues/6133

You can link your other pull requests to this one. And yes, you can try PR and introduce some code smells to see if it works. I activate the config at Sonarcloud so all the pull requests should be decorated by a Sonarcloud comment

**Comment by zhyd1997** [comment]
Hi 
Screenshot 2023-05-02 at 15 49 01
@pascalgrimaud 

I need the information here:

Screenshot 2023-05-02 at 15 48 28

**Comment by pascalgrimaud** [comment]
@zhyd1997 : have a look at https://github.com/jhipster/jhipster-lite/blob/main/.github/workflows/github-actions.yml#L81

**Comment by pascalgrimaud** [comment]
Yes, it looks nice @zhyd1997 ! Thanks a lot.
I'll have a close look on this after my day work :)

**Pull request closed without merging**
