### PR TITLE
Upgrade node and npm

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2499

To be honest I don't know (at all) if this is a good idea / a good way to do that (not even sure that work, can't really test automatic dependabot updates on that)

@qmonmert any advice on that?

### CODE REVIEW

**Comment by qmonmert** [comment]
First time that I will see dependabot working on npm and node versions. The idea is good but I am afraid that tests are ok but the reality will be different 😅 but we can try

**Review by qmonmert — APPROVED** [review]

**Comment by DamnClin** [comment]
Yep, I really don't think that'll do but let's try...

**Comment by qmonmert** [comment]
🎸

**Comment by DamnClin** [comment]
Looks like it work: https://github.com/jhipster/jhipster-lite/pull/2984

BUT I don't know if we want to update to the latest versions (cc @pascalgrimaud)

**Comment by qmonmert** [comment]
Good but 18.0.7 is not a LTS ...

**Comment by DamnClin** [comment]
Yep, this is what bothering me...

**Pull request merged**
