### PR TITLE
Problem: use get version, managed by dependabot

### PR DESCRIPTION
**Pull request by DanielFran**
- related to https://github.com/jhipster/jhipster-lite/issues/615

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud Seems there is issues with last changes related with user liquibase XML...

**Comment by pascalgrimaud** [comment]
@DanielFran : strange, the CI is ok, in main branch. I'll have a look

**Comment by pascalgrimaud** [comment]
@DanielFran : strange, the CI is ok, in main branch. I'll have a look

**Comment by pascalgrimaud** [comment]
@DanielFran : strange, the CI is ok, in main branch. I'll have a look

**Comment by pascalgrimaud** [comment]
@DanielFran : should be fixed in main branch, can you rebase plz?

**Review by pascalgrimaud — APPROVED** [review]

**Pull request merged**
