### PR TITLE
Sonar: Fix tag em with role=img

### PR DESCRIPTION
**Pull request by qmonmert**
Fix https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AY8KyTGBADMkkF4M9RVl&tab=code

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud an idea for the build failed? :)

**Comment by pascalgrimaud** [comment]
I think we need to add the new key related to gradle. Waiting @murdos or @atomfrede

**Comment by qmonmert** [comment]
ok

**Comment by murdos** [comment]
I'm not sure it's related to develocity, since other builds look fine, and there's also another error:
> 9 21.87 [INFO] --- frontend:1.15.0:npm (build front) @ jhlite ---
#9 21.92 [INFO] npm not inheriting proxy config from Maven
#9 21.92 [INFO] Running 'npm run build' in /code/jhipster-app
#9 22.23 [INFO] 
#9 22.23 [INFO] > jhlite@1.7.1-SNAPSHOT build
#9 22.23 [INFO] > vue-tsc -p tsconfig.build.json --noEmit && vite build --emptyOutDir && tikui-core build
#9 22.23 [INFO] 
#9 22.24 [INFO] sh: 1: vue-tsc: not found

@qmonmert: I'm gonna add temporarily commits to your branch to check if it's related, I'll then revert them.

**Comment by murdos** [comment]
The issue is reproducible locally if you try to build the docker image from this branch.
It think the problem comes from the build cache that is corrupted:
> #9 21.14 [INFO] --- frontend:1.15.0:npm (npm install) @ jhlite ---
#9 21.86 [INFO] Loaded from the build cache, saving 0.769s

> root@a0c996edfa73:/code/jhipster-app# ls node_modules/vue-tsc/bin/
root@a0c996edfa73:/code/jhipster-app#

**Comment by murdos** [comment]
@qmonmert : you should try to rebase your branch 🙂

**Comment by qmonmert** [comment]
@murdos done but it doesn't work :/

**Comment by murdos** [comment]
@qmonmert : I rebased the branch, and merged the PR since the build was green :)

**Comment by qmonmert** [comment]
@murdos thanks what was the problem?

@pascalgrimaud quality ✅
image

**Pull request merged**
