### PR TITLE
Sonar: Rename this generic name to match the regular expression

### PR DESCRIPTION
**Pull request by qmonmert**
Fix:
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dd8AOAljwIYo6_
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dd8AOAljwIYo7A
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dd8AOAljwIYo7B
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dt8AOAljwIYo7C
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dt8AOAljwIYo7D
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6dt8AOAljwIYo7E
- https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&resolved=false&id=jhipster_jhipster-lite&open=AZBcO6d_8AOAljwIYo7F
- ...

### CODE REVIEW

**Review by murdos — COMMENTED** [review]
I think we should rather disable this Sonar rule.
Current code is more expressive and maintainable than the one enforced by Sonar.

**Comment by qmonmert** [comment]
@murdos ok but if we disable a lot of rules, why have Sonar?

**Comment by murdos** [comment]
> @murdos ok but if we disable a lot of rules, why have Sonar?

@qmonmert : A lot of rules are interesting, and some are not. We can't directly configure the applied rules, they're defined in the quality profile defined on the SonarQube server: https://sonarcloud.io/organizations/jhipster/quality_profiles/show?name=Sonar+way&language=java
It's similar to eslint, that provides a lot of rules. Some are part of the recommended config, and some are just provided but not enabled, and each project/team decides what rules are applied.

**Review by murdos — APPROVED** [review]

**Comment by pascalgrimaud** [comment]
shouldn't it be applied to generated config too ?

**Comment by qmonmert** [comment]
@pascalgrimaud done here https://github.com/jhipster/jhipster-lite/pull/10212

**Pull request merged**
