### PR TITLE
Add a small documentation for ApprovalTests

### LINKED ISSUE #9658: Add a small documentation for ApprovalTests
Following #9607 : a documentation should be generated with a few examples, as done for [Property-based Testing](https://github.com/jhipster/jhipster-lite/blob/3266169af076475fb0b00a6e0330128371414407/src/main/resources/generator/server/javatool/pbt/property-based-testing.md):
- simple example
- example with a parametrized junit test
- example of use of [combinations](https://github.com/approvals/ApprovalTests.Java/blob/master/approvaltests/docs/tutorials/GettingStarted.md#generate-combinations-of-parameter-values)

### PR DESCRIPTION
**Pull request by Harsh4902**
- Added documentation for Approval Test
- Fixes #9658

### CODE REVIEW

**Comment by Harsh4902** [comment]
@murdos How can I fix this formatting error?

**Comment by fabienpuissant** [comment]
> @murdos How can I fix this formatting error?

npm run prettier:format 😃

**Comment by pascalgrimaud** [comment]
all the code is formatted automatically using husky git hook, but you need to launch `npm ci` the first time you clone the project, then regularly as the dependencies are updated each day

**Review by murdos — CHANGES_REQUESTED** [review]
This new documentation is not included in the generated application.
You need to generates it.
Start with completing existing tests for this module, as done with the other similar module: https://github.com/jhipster/jhipster-lite/blob/3266169af076475fb0b00a6e0330128371414407/src/test/java/tech/jhipster/lite/generator/server/javatool/pbt/domain/PropertyBasedTestingModuleFactoryTest.java#L24

And then make the test pass :) (Hint: study the PropertyBasedTestingModuleFactory to understand what you should do)

**Review by murdos — APPROVED** [review]

**Pull request merged**
