### PR TITLE
Support for using YAML format for spring configuration

### PR DESCRIPTION
**Pull request by murdos**
Limitation: Handling of comments is currently not supported (I'll tackle that in a separate PR, that will probably also redesign "block property" comments).

See #1956

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@murdos : can you rebase, so I think we can go ahead and merge it

**Comment by murdos** [comment]
@pascalgrimaud : done

**Comment by pascalgrimaud** [comment]
@murdos : small failed test

**Comment by murdos** [comment]
> @murdos : small failed test

Fixed and merged :)

**Pull request merged**
