### PR TITLE
Svelte - fix: npm run check

### PR DESCRIPTION
**Pull request by qmonmert**
Fix:
image

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Adding a bounty on this, for all the recent work for svelte, angular, react, etc.
Thanks @qmonmert

**Comment by qmonmert** [comment]
@pascalgrimaud thanks 🙂

**Comment by pascalgrimaud** [comment]
After having a quick look, I think we should keep:

```
"@/*": ["main/webapp/app/*"],
```

The correct fix should be:

```
import App from '@/common/primary/app/App.svelte';
```

Instead of 

```
import App from '@webapp/app/common/primary/app/App.svelte';
```

**Comment by pascalgrimaud** [comment]
Anyway I'm not a Svelte user, I'm letting you decide what's the best :)

**Comment by qmonmert** [comment]
@pascalgrimaud indeed, two solutions work, maybe your is best, I update the PR

**Comment by qmonmert** [comment]
`npm t` does not work with your solution @pascalgrimaud 🤔

**Comment by pascalgrimaud** [comment]
Need probably to update the vitest config ts:

```
    alias: [
      { find: '@', replacement: path.resolve(__dirname, 'src/main/webapp/app') },
      { find: '@assets', replacement: path.resolve(__dirname, 'src/main/webapp/assets') },
    ],
```

**Comment by qmonmert** [comment]
> 

you try on your machine, it does not work for me

**Comment by pascalgrimaud** [comment]
So let's keep your 1st solution, we'll see later to improve this part

**Comment by qmonmert** [comment]
I think I find solution I update

**Comment by qmonmert** [comment]
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/117655 🙂

**Comment by pascalgrimaud** [comment]
@qmonmert : approved, thanks for your work

**Pull request merged**
