### PR TITLE
Feature/issue 5181 cassandra migration support 

### LINKED ISSUE #877: Spring Boot Database: Cassandra
Like generator-jhipster is currently doing, the goal of this issue would be to help users to add configuration for cassandra into their application.

### PR DESCRIPTION
**Pull request by Yourgene**
Fixes https://github.com/jhipster/jhipster-lite/issues/5181

This module adds cassandra schema migration support.

The way it works is the same as in jhipster-generator, with small adaptations.

2 things I want to highlight :
- #2611 is not yet done, so RegexReplacers are used to append listeners to spring.factories in this module. I'm working on the issue in parallel, and will change this module behaviour when #2611 is done (most probably after this PR is merged).
- [This solution](https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/#cassandra.schema-management.initializing.config) can probably be used to apply schema changes, instead of relying on a docker container as it is the case now. Going this way would reduce the amount of code in`src/docker` and `src/test`

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Looks good to me.

@murdos : do you have time to have a quick look too plz?

**Comment by murdos** [comment]
> Looks good to me.
> 
> @murdos : do you have time to have a quick look too plz?

Sure, I'll take a look this week.

**Comment by pascalgrimaud** [comment]
ahaha sorry, it will be a post review, as it's already merged :p

**Comment by Yourgene** [comment]
Hi, I claimed the bug bounty for this PR : [link](https://opencollective.com/generator-jhipster/expenses/122473)

**Comment by pascalgrimaud** [comment]
@Yourgene : approved :-)

**Pull request merged**
