### PR TITLE
Maven: Add Plugin management and configuration

### PR DESCRIPTION
**Pull request by swarajsaaj**
- Allow maven plugins to be added in `pluginManagement`
- Allow deeper configuration for maven plugins
  - Executions
    - Phase
    - Goals
  - Configuration

This PR is pre-requisite to #284

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Does it cover all possible configuration? PluginManagement is the most complex part of Maven, and modeling this part, is not easy.

If it's too difficult, there are some alternatives:
- use git patch like https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/mvc/security/jwt/jwt-security-annotation-processor.patch
- add a needle like you did `<!-- jhipster-needle-maven-add-plugin-management -->` and simply use replace: https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/common/domain/FileUtils.java#L127-L134

**Comment by swarajsaaj** [comment]
> Does it cover all possible configuration? PluginManagement is the most complex part of Maven, and modeling this part, is not easy.

Hi @pascalgrimaud, Yes, I realized its complex :), but wanted to try something better than patch/text-replacement.

This is an attempt to generate the configuration using Java code. Mainly covers `<execution>` and `<configuration>` sections. For `configuration` I have tried to model it into two types of nodes:-
- `PluginConfigurationValue` - Meant for simpler value nodes like `<source.dir>/tmp</source.dir>`
- `PluginConfigurationContainer` - For complex nested tree-like configuration of any plugin, (the `children` of this node can again be of type ``PluginConfigurationValue` or `PluginConfigurationContainer` to allow complicated configurations).

Currently it does not cover `reportSets`, `inherited` and nested `dependencies` within plugin. What do you think of this strategy?

**Comment by pascalgrimaud** [comment]
When I look at the possible generated `pom.xml`, I don't think it's doable in Java: https://github.com/jhipster/jhipster-sample-app/blob/main/pom.xml :-D

So my advice would be to keep as simple as possible: regexp + text block (with Java 17) and it's done! :)

**Comment by swarajsaaj** [comment]
Though its closely possible with this approach as seen in this test case, but maybe its an overkill for something we won't really need too much control on (a replace text might be just okay) :)
 https://github.com/jhipster/jhipster-lite/blob/3a9840296b371d823fa2262f55d97a42609c37b1/src/test/java/tech/jhipster/lite/generator/buildtool/maven/domain/maven/MavenTest.java#L227-L264

**Comment by pascalgrimaud** [comment]
Yes sure it's possible. But as you said, maybe it's overkill. I'd vote for using replace

**Comment by swarajsaaj** [comment]
I ll close this PR, in favour of using a regex-replace method. Will raise a new PR for that.

**Pull request closed without merging**
