### PR TITLE
fix and improve custom jhlite instructions

### LINKED ISSUE #8503: Custom JHLite - instructions in markdown
We need to check if the instructions in markdown work well.
The last time I tried (v1.0.0 if I remember well), I need to do some changes and the Cucumber tests didn't work (probably related to upgrade to last version of Spring Boot)

To do here:
- check the instructions and update if necessary
- if there are some bugs, it needs to be fixed

### PR DESCRIPTION
**Pull request by renanfranca**
Fix #8503

### CODE REVIEW

**Comment by renanfranca** [comment]
@pascalgrimaud: I followed the instructions in module-creation.md and made fixes when things didn't work as expected. I also enhanced the detail of the exceptions when the Cucumber tests failed.

**Comment by pascalgrimaud** [comment]
Thanks @renanfranca 
I'd like to have time to give it a try. If you can push a sample project using JHLite Custom on GitHub, so I can confirm it works as expected

**Comment by renanfranca** [comment]
> Thanks @renanfranca I'd like to have time to give it a try. If you can push a sample project using JHLite Custom on GitHub, so I can confirm it works as expected

I'll do it 👍

**Comment by renanfranca** [comment]
@pascalgrimaud : A sample creating a new module at a custom jhlite project by following the instructions: https://github.com/renanfranca/f800dd16-3316-4294-9835-953bf6ecaf1a

**Comment by pascalgrimaud** [comment]
Thanks for your work @renanfranca !

**Pull request merged**
