### PR TITLE
Migrate landscape css to tikui

### LINKED ISSUE #3970: Migrate landscape css to tikui
The landscape css partly remains in the .vue file. Should be put in tikui

### PR DESCRIPTION
**Pull request by nassimerrahoui**
fix #3970

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@nassimerrahoui : can you edit your description in this PR and put this `fix #3970` so the ticket will be closed automatically once this PR is merged :)

**Comment by pascalgrimaud** [comment]
Maybe you can have a quick look on this plz @Gnuk ?

**Comment by nassimerrahoui** [comment]
> Maybe you can have a quick look on this plz @Gnuk ?

For the moment it is not done, I just already started this

**Comment by nassimerrahoui** [comment]
> @nassimerrahoui : can you edit your description in this PR and put this `fix #3970` so the ticket will be closed automatically once this PR is merged :)

Done 👍

**Comment by nassimerrahoui** [comment]
I am closing this PR because there is already one in progress #2894

**Pull request closed without merging**
