### PR TITLE
Add Gitpod generation

### PR DESCRIPTION
**Pull request by MSaguer**
Add gitpod configuration for generated project
New setup tool card in front part

Close https://github.com/jhipster/jhipster-lite/issues/1628

### CODE REVIEW

**Comment by MSaguer** [comment]
Prerequesites for workspace preparation by gitpod
- Maven has been initialized and mvnw has execution rights
- npm install has been launched once and package-lock.json stored under Git

If these prerequesites are not done, workspace initialisation can be skipped to open directly the workspace and perform required actions.

**Comment by MSaguer** [comment]
I should have mentionned in the PR opening that I've also added the codespace button in the front.

**Comment by pascalgrimaud** [comment]
Can you add a README with a description of what is it used for, plz?

**Comment by pascalgrimaud** [comment]
We can add the README in another PR

**Pull request merged**
