### PR TITLE
Modules landscape

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/2996
Related to https://github.com/jhipster/jhipster-lite/issues/1666

This is a first version, still not really usable as is, here is the beginning of the tree: 
level1-2

This first part is OK but then comes a problem when we have modules depending on multiple levels, here is one of the worst part (bottom of levels 4 to 6): 
level4-6

Easy problems to tackle next: 
* Descriptions are pretty bad, we must do a full review of them;
* Some modules must be split (see https://github.com/jhipster/jhipster-lite/issues/2997).

Harder problems:
* Some dependencies are probably not good. The messing lines may indicate that, we probably need to rethink some of the dependencies;
* Reaching something really readable...
* Were do we put the form with all properties for application of multiple modules?
* And probably lot of other but I think this is an important first step!

### CODE REVIEW

**Comment by DamnClin** [comment]
An idea may be to merge all dependencies from a feature to something so we can have less lines

**Comment by DamnClin** [comment]
Back to draft: just saw that resizes send the lines very far, need to fix that :)

**Comment by DamnClin** [comment]
Overnight though: 

* The application form can be a fixed block top left;
* We should give lots of hints during selection: 
  * Cleary mark non selectable modules
  * Change line shape (full vs dotted) for links to selected modules VS not selected modules
  * Change line and box color for selected module (use primary)
  * Animate linked elements when going over a not selected module (something like a color change)

But all this will be in dedicated PR since this one is already huge and we first need to reorganize some modules

**Comment by hdurix** [comment]
Good idea to split PRs :smile: 

I've just read this PR, seems good. Nice work!!

**Comment by DamnClin** [comment]
> Good idea to split PRs
Yep... sorry for this one...

> I've just read this PR, seems good. Nice work!!
Still not really usable but I think this is an interesting step to have a really usable JHlite

**Comment by hdurix** [comment]
Do you think it could be relevant to have only 1 line from a module to a feature? Instead of having 1 line for each module of the feature?

image

Here a line from `springboot` to `jpa-persistence`.

Do you think that in a feature, modules could have different dependencies?

**Comment by DamnClin** [comment]
Not for all cases (because sometimes all modules in the same feature don't share the same dependencies) but this is this comment: 

> An idea may be to merge all dependencies from a feature to something so we can have less lines
> 
> In the current landscape this removes 17 connections, it require some effort but it's probably worth it

**Pull request merged**
