### PR TITLE
Refactoring: Landscape.vue

### LINKED ISSUE #7590: Refactoring: Landscape.vue
The CSS part should be moved into **style/** folder

### PR DESCRIPTION
**Pull request by qmonmert**
- [x] Fix #7590 
- [x] Start refactoring `src/main/webapp/app/assets/global.scss`

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud I think we can merge like that, no `<style lang="scss">` in Vue components now 🙂
After that, we could improve Tikui adding all components (already created) in atom, molecule, organism... And working on 
 CSS files (tikui CSS vs globals CSS) in the project

**Comment by qmonmert** [comment]
@pascalgrimaud moreover if you can test this PR to see if CSS is not broken because the Landscape is the main component 🙂

**Comment by pascalgrimaud** [comment]
I think it's not exactly the same page than in main branch:
image

Your current PR:
image

- green module
- some thing in minimap too

**Comment by qmonmert** [comment]
thanks @pascalgrimaud 🙂 fixed

**Pull request merged**
