### PR TITLE
Improve logback configuration in generated apps

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by DanielFran** [comment]
@pascalgrimaud in the generator-jhipster we are now using only the console-appender by default
https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/resources/logback-spring.xml#L14

**Comment by pascalgrimaud** [comment]
thanks @DanielFran 
I'll have a look to have the most default config as possible

**Comment by DanielFran** [comment]
@pascalgrimaud 

Following https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.logging.logback, legacy base.xml file is provided for compatibility with earlier versions of Spring Boot 1.
base.xml includes actually default + console appended + file appender

In generator jhipster we review the configuration of logback to define only console appender. For that it uses only default+console-appender XML
Example from spring-boot documentation:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
    <root level="INFO">
        <appender-ref ref="CONSOLE" />
    </root>
    <logger name="org.springframework.web" level="DEBUG"/>
</configuration>
````

So, I believe you need to review the config, adding console-appender and keeping base.xml is not good.

**Comment by pascalgrimaud** [comment]
Can you provide a PR @DanielFran plz ?
It will help you to understand our templates in this projet :-)

**Pull request merged**
