### PR TITLE
Add cypress react

### LINKED ISSUE #776: React: add cypress

### PR DESCRIPTION
**Pull request by flcarre**
fix #776 

POST /api/vite/react
POST /api/vite/react/cypress
npm install
npm run cypress:open
npm run cypress:run

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@flcarre : can't you ?

image

**Comment by flcarre** [comment]
nope i can't

**Comment by pascalgrimaud** [comment]
@flcarre : can you rebase plz?

**Comment by pascalgrimaud** [comment]
Just tried it, and it doesn't work:

I started the project:

```
./mvnw spring-boot:run
```

I launch:

```
npm run cypress:run
```

image

**Comment by flcarre** [comment]
work for me, have you init the react project with `/api/vite/react` ? The cypress api just add cypress to an existing react project
image

**Comment by pascalgrimaud** [comment]
Yes, I did it in a generated project: reactapp
I think it's because Cypress launch test in localhost:3000 instead of localhost:{{serverPort}} 
The default backend is localhost:8080

**Comment by pascalgrimaud** [comment]
@flcarre : I'm taking care of this
- update the branch with last change in main
- fixing merge conflicts
- fixing the last code smells
- clean some code
- merge it
- so @Bolo89 can refactorize this part to make it common with Vue

**Pull request merged**
