### PR TITLE
Replace sinon by vitest in tests files (generated Vue app)

### PR DESCRIPTION
**Pull request by qmonmert**
Related to #7463 

Fix https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&id=jhipster_jhipster-lite-sample-app&open=AYqnI_SaWvNZCKI35ulv

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud when https://sonarcloud.io/summary/new_code?id=jhipster_jhipster-lite-sample-app starts a new analysis?

**Comment by pascalgrimaud** [comment]
@qmonmert : at the next release :-)

**Comment by qmonmert** [comment]
@pascalgrimaud ok :) we can't start a new analysis manually?

**Comment by pascalgrimaud** [comment]
I could update the current main branch. Let me do this

**Comment by qmonmert** [comment]
@pascalgrimaud 👍

**Comment by pascalgrimaud** [comment]
@qmonmert : done here https://github.com/jhipster/jhipster-lite-sample-app/commit/78a8829c40790c0ba22c6a9bf00e2f7cb00c6d0a so the sonarcloud analysis should trigger

**Comment by qmonmert** [comment]
@pascalgrimaud thanks

**Comment by qmonmert** [comment]
https://sonarcloud.io/summary/overall?id=jhipster_jhipster-lite-sample-app perfect :)

**Pull request merged**
