### PR TITLE
Move to vitest

### PR DESCRIPTION
**Pull request by Gnuk**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I think it's a good move, we should try to achieve this

**Comment by pascalgrimaud** [comment]
@Gnuk : for your information, this PR https://github.com/jhipster/jhipster-lite/pull/3866 can help 

But there are still some issue, related to coverage

**Comment by Gnuk** [comment]
Waiting for https://github.com/vitest-dev/vitest/issues/2245 to be merged before merging this one.

**Comment by Gnuk** [comment]
It's now ready, thank you @AriPerkkio for the help on vitest :)

**Comment by Gnuk** [comment]
I'll claim $300 fot this issue.

**Comment by pascalgrimaud** [comment]
Thanks for your work @Gnuk and @AriPerkkio !!!

Plz follow this https://www.jhipster.tech/bug-bounties/#-bug-bounties to claim each part of bounty

As discussed between you, 300 for @Gnuk and 200 for you @AriPerkkio : hope it's ok :-)

Don't forget to comment this pull request with the open collective link, so I can approve it

**Comment by Gnuk** [comment]
Claimed: https://opencollective.com/generator-jhipster/expenses/105341

**Comment by AriPerkkio** [comment]
Claimed: https://opencollective.com/generator-jhipster/expenses/105342

**Comment by pascalgrimaud** [comment]
@Gnuk : approved

**Comment by DamnClin** [comment]
Played with it. The "setup" (npm run test:watch) is a little bit long but then we finally have acceptable feedback loops on TS tests!

**Pull request merged**
