### PR TITLE
Add cypress in common client

### PR DESCRIPTION
**Pull request by Bolo89**
- fix https://github.com/jhipster/jhipster-lite/issues/991

### CODE REVIEW

**Comment by Bolo89** [comment]
I need to add custom prettier for json to keep the default tsconfig.json format

**Comment by pascalgrimaud** [comment]
> I need to add custom prettier for json to keep the default tsconfig.json format

@Bolo89 : can you point me where you did this? so I can understand better what you have in mind

**Comment by Bolo89** [comment]
> > I need to add custom prettier for json to keep the default tsconfig.json format
> 
> @Bolo89 : can you point me where you did this? so I can understand better what you have in mind

To Build à front project with cypress, I had to exclude the test files linked to cypress in the main tsconfig.json. So I have written à method in JsonUtils to convert the tsconfig.json to jsonnode, add the pattern in the array of excluded and convert the node to string.
But the converted string had some extra spaces
Exemple
`json
{
   ''field'' : [ ''v1'', ''v2'' ] 
}
`
So I use custom json prettifier in JsonUtils.

**Review by pascalgrimaud — DISMISSED** [review]

**Comment by Bolo89** [comment]
Bounty claimed at: https://opencollective.com/generator-jhipster/expenses/71871

**Comment by pascalgrimaud** [comment]
@Bolo89 : approved

**Pull request merged**
