### PR TITLE
Replace Some videos By Some Videos in README.md

### PR DESCRIPTION
**Pull request by bakus32**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Thanks @bakus32 but you need to sign the cla

**Comment by anderskristian** [comment]
Such small documentation change must be easy to approve 🐥

**Comment by DamnClin** [comment]
> Such small documentation change must be easy to approve 🐥

They are :). We just need the CLA signature to avoid further problems. This is a one time action

**Comment by pascalgrimaud** [comment]
as no news from the author, can't be merged without the CLA, so closing this. I'll reopen as soon as it is signed

**Pull request closed without merging**
