### PR TITLE
Generator: add missing test for RestManagementRepository

### PR DESCRIPTION
**Pull request by qmonmert**

### CODE REVIEW

**Comment by qmonmert** [comment]
@pascalgrimaud ok to merge this PR and #10949 ?

**Comment by murdos** [comment]
@qmonmert : these tests are really testing implementation details.
I'd like to not require them by using code coverage from component tests instead: https://github.com/jhipster/jhipster-lite/pull/10950

**Comment by pascalgrimaud** [comment]
I agree : `these tests are really testing implementation details`

But should we totally exclude what is in `infrastructure` folder ? But in this case, we can write bad + wrong code in infrastructure, so Cypress will become mandatory to protect that.

My small opinion (and probably wrong) would be:
- we can merge this one
- it's already done and won't take time to maintain
- for real projects, the user will be free to ignore infrastructure folder or not

**Comment by qmonmert** [comment]
@murdos ok to merge this?

**Comment by murdos** [comment]
Go ahead.
When I'm going to finish https://github.com/jhipster/jhipster-lite/pull/10950, I'll evaluate if I remove it or not.

**Pull request merged**
