### PR TITLE
Use checkstyle to check for unused imports during build

### PR DESCRIPTION
**Pull request by murdos**
Following https://github.com/jhipster/jhipster-lite/pull/7226#issuecomment-1685393587

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@murdos : what do you think about adding this as a new module too ?

**Comment by murdos** [comment]
> @murdos : what do you think about adding this as a new module too ?

It was indeed my intention. Do you think I should do it in the same PR?

**Comment by pascalgrimaud** [comment]
@murdos : no it's better to do in a separate PR, as it's a really simple module and it will be another good example for new contributors :-)

**Comment by pascalgrimaud** [comment]
@murdos : for your information, just tested it and it works well, excepting for class in src/test, so I think it would be nice to include them too, what do you think?

**Comment by murdos** [comment]
> @murdos : for your information, just tested it and it works well, excepting for class in src/test, so I think it would be nice to include them too, what do you think?

Sure! I thought that this was the default behavior of the maven plugin, but it is not :/

**Pull request merged**
