### PR TITLE
feature(gradle): remove gradle-java from hidden resources

### PR DESCRIPTION
**Pull request by murdos**
Gradle support is now nearly complete, it can be enabled officially, in a beta status 🥳

### CODE REVIEW

**Review by renanfranca — APPROVED** [review]
That's so satisfying!!! Thabks, everyone!!! We finally made it!!! 🥳🥳🥳🥳🥳

**Comment by renanfranca** [comment]
No more need to comment gradle line at application.yml 😎🫂☺️🙌

**Comment by atomfrede** [comment]
Great work!

**Comment by atomfrede** [comment]
Great work!

**Pull request merged**
