### PR TITLE
Restructuring of generator frontend tests

### PR DESCRIPTION
**Pull request by murdos**
- Rename webapp tests folder from src/test/javascript to src/test/webapp : 
  - So src/main/webapp matches src/test/webapp
  - Also frontend tests are not limited to javascript code, this also includes components and e2e tests
- Rename webapp unit tests folder to src/test/webapp/unit
- webapp tests: isolate component tests from e2e tests
- rename e2e folder and remove component tests from e2e folder

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Totally agree with this change, although it's a breaking change
Just wonder if `src/test/webapp` could / should be a variable ? in case we have a full typescript application

**Comment by murdos** [comment]
@pascalgrimaud : I'm glad you agree :) I'll try to fix failing test on windows so we can merge it.
The current PR is only for the generator, I wanted to setup things cleanly before trying something for #9491
It's also a prerequisite for something I want to investigate: merging code coverage between unit tests and components tests for frontend (that would allow removing some dumb unit tests).
If things are satisfying, we can then evolve generated apps :)

**Comment by murdos** [comment]
FYI: there's an issue with tikui-serve and component tests ran with Cypress on Windows, I'll need to discuss that with @Gnuk when he's available.

**Comment by Gnuk** [comment]
> FYI: there's an issue with tikui-serve and component tests ran with Cypress on Windows, I'll need to discuss that with @Gnuk when he's available.

I'm back next week :)

**Comment by murdos** [comment]
@pascalgrimaud : this is now ready for merge (there's no breaking change since it only relates to the internal of the generator) :) With the help of @Gnuk I fixed the windows build.

**Comment by pascalgrimaud** [comment]
can you fix the conflict plz @murdos ?

**Comment by murdos** [comment]
@pascalgrimaud : conflicts are fixed

**Pull request merged**
