### PR TITLE
Update dependencies with Node 22.11.0

### PR DESCRIPTION
**Pull request by qmonmert**
Related to #11522 

Fix #11518 
Fix #11519
Fix #11520
Fix #11521
Fix #11511

### CODE REVIEW

**Review by murdos — CHANGES_REQUESTED** [review]
I don't think that this will solve the issue. Please let me try something else

**Comment by qmonmert** [comment]
image

@pascalgrimaud Ci uses node 22.12.0

**Comment by qmonmert** [comment]
> image
> @pascalgrimaud Ci uses node 22.12.0

cc @murdos

**Comment by murdos** [comment]
> @pascalgrimaud Ci uses node 22.12.0

@qmonmert : yes, that's what I identified too. And https://github.com/jhipster/jhipster-lite/pull/11525 should fixes that.

**Pull request closed without merging**
