### PR TITLE
Init: use cucumber for tests

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by DamnClin** [comment]
What do you think, the usage is easy enough? In this case you can delete your Rest controller IT and your domain UnitTest I think, you'll get the same coverage but more value since it's actually testing stuff

**Comment by pascalgrimaud** [comment]
I already deleted the InitResourceIT

About the Unit test in Domain and Application Service, I'm working on another PR to use the new system with modules, so I'll delete these files in another PR. Then, we'll have a clean "init" context :-)

**Comment by DamnClin** [comment]
Careful you don't need https://github.com/jhipster/jhipster-lite/issues/1787 to make this happen (the work on this is at step 0 :D: I have a ticket)

**Comment by pascalgrimaud** [comment]
ahaha yes, that's why I choose a context which doesn't need Java dependencies :)

**Pull request merged**
