### PR TITLE
Modules deactivation

### PR DESCRIPTION
**Pull request by DamnClin**
Close https://github.com/jhipster/jhipster-lite/issues/3484

### CODE REVIEW

**Comment by DamnClin** [comment]
Waiting for https://github.com/jhipster/jhipster-lite/pull/3591 to add documentation in custom JHLite

**Review by pascalgrimaud — APPROVED** [review]
could you disable all the banner modules too plz?

**Comment by DamnClin** [comment]
> could you disable all the banner modules too plz?

Why??? If we don't want a module in the main JHLite instance we should delete it! For me we need https://github.com/jhipster/jhipster-lite/issues/3049

**Comment by pascalgrimaud** [comment]
Oh last point: I was suggesting to disable it because it will reduce the size of the tree, that's all :-D

**Comment by DamnClin** [comment]
Ok, I'll disable it with a tag so

**Pull request merged**
