### PR TITLE
Revert Node to 22.11.0

### LINKED ISSUE #11522: Build failed for react app
Current reactapp failed to build.
We need to fix it, so we can merge new Spring Boot 3.4 then release :)

Do you want to work on this @qmonmert ?

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #11522 

Related to https://github.com/nodejs/node/issues/56155

### CODE REVIEW

**Comment by murdos** [comment]
Thanks @qmonmert !

**Comment by qmonmert** [comment]
@murdos :)

**Comment by pascalgrimaud** [comment]
So the problem was related to Node!
Thanks

**Comment by qmonmert** [comment]
@pascalgrimaud :)

**Pull request merged**
