### PR TITLE
safely remove libs version reference

### LINKED ISSUE #10060: Gradle: removeDependency doesn't remove unused version at `libs.versions.toml`
Following #6977 gradle removeDependency needs to be handled.
I generated the [sample app using Gradle build tools](https://github.com/renanfranca/sampleapp-gradle-dont-remove-unused-version). Three versions aren't used anywhere (neither in [`libs.versions.toml`](https://github.com/renanfranca/sampleapp-gradle-dont-remove-unused-version/blob/main/gradle/libs.versions.toml) nor in [`build.gradle.kts`](https://github.com/renanfranca/sampleapp-gradle-dont-remove-unused-version/blob/main/build.gradle.kts)):

- `mockito = "5.12.0"`
- `assertj = "3.26.0"`
- `junit-jupiter = "5.10.2"`

TO-DO: Implement safe removal of versions
- [x] When removing the dependency manager
- [x] When removing a direct dependency
- [x] Profile: When removing the dependency manager
- [x] Profile: When removing a direct dependency

### PR DESCRIPTION
**Pull request by renanfranca**
Fix #10060  (see the TO-DO at issue description)

### CODE REVIEW

**Review by murdos — APPROVED** [review]
Awesome, thanks! :)

**Comment by renanfranca** [comment]
> Awesome, thanks! :)

Thanks 😊

**Comment by renanfranca** [comment]
@murdos : Is it a generic error? https://github.com/jhipster/jhipster-lite/actions/runs/9783882769/job/27014572353#step:21:1

**Comment by murdos** [comment]
> @murdos : Is it a generic error? https://github.com/jhipster/jhipster-lite/actions/runs/9783882769/job/27014572353#step:21:1 

@renanfranca : Sorry, I've no idea :man_shrugging:

**Comment by renanfranca** [comment]
I will let it go for now and keep watching it. I tried to rerun all jobs and got a Sonar not initialized error, but when I ran it on localhost, it worked fine.
https://github.com/jhipster/jhipster-lite/actions/runs/9783882769/job/27041337459

**Comment by renanfranca** [comment]
@pascalgrimaud: Bounty Claimed https://opencollective.com/generator-jhipster/expenses/210043. Thanks 😀✌

**Comment by pascalgrimaud** [comment]
@renanfranca : approved

**Pull request merged**
